ruby/reline

- lib/reline.rb
- lib/reline/key_stroke.rb
- test/key_stroke_test.rb
> Add key stroke.

- .gitignore
- .travis.yml
- Rakefile
- download-test_readline.sh
Add RubyCore [`test/readline`](https://github.com/ruby/ruby/tree/trunk/test/readline) to CI test.
```shell
$ sh ./download-test_readline.sh
$ rake ci-test
```
> Add RubyCore test/readline to CI test

- Rakefile
- download-test_readline.sh
Test tools path has changed.
see: https://github.com/ruby/ruby/commit/c3c0e3f5c9444c197779cb242de46dfffda79dec
Fixed download path.
> Fix to test tools download path in CI

- lib/reline/line_editor.rb
@old_trap is the string "DEFAULT" and not a callable object (Proc)
if there are no other signal handlers for SIGINT signal to chain.
Found running 'make test-all' running Ruby's test suite and CTRL-C'ing the terminal, resulted in NoMethodError 'call' on string "DEFAULT".
> fix issue with 'SIGINT' handling in LineEditor#reset

- lib/reline.rb
RUBY_PLATFORM on JRuby is always "java", so it will not reflect the host operating system. This regex appears to be the consensus way to detect Windows based on a search of Ruby code on Github:
https://github.com/search?q=%2Fmswin%7Cmsys%7Cmingw%7Ccygwin%7Cbccwin%7Cwince%7Cemc%2F&type=Code
The regex appears to date back to at least 2012, judging by @enebo's comment here: https://stackoverflow.com/questions/11784109/detecting-operating-systems-in-ruby
The "os" gem is mentioned there as well, but probably is overkill (and would also need to be shipped with Ruby).
> Use host_os from RbConfig to detect host OS.

- lib/reline/line_editor.rb
- test/reline/test_key_actor_emacs.rb
To reproduce this bug, type one character into irb, then press the
delete key on your keyboard.
> Don't crash when deleting at the end of the line

- .github/workflows/ubuntu-rvm-with-irb.yml
> Add irb test in CI.

- lib/reline/ansi.rb
Enable `Ctrl+Y`, which is bound with it by default on BSD-like systems, for editing.
> Undefine DSUSP key

- lib/reline/line_editor.rb
Previously, `:vi_insert` mode did not match any of the cursor-reset cases when navigating history. This could allow the cursor to go passed the end of the line, for example when going to a previous line, moving the cursor, and then going back to the current empty line. Trying to move the cursor left or right afterwards results in an exception. I couldn't get the arrow key codes working in the tests or I would have added one like:
```ruby
def test_insert_mode_history
Reline::HISTORY.concat(%w{abcd 123 AAA})
assert_line('')
assert_byte_pointer_size('')
assert_cursor(0)
assert_cursor_max(0)
input_keys("\C-[[A")
assert_line('AAA')
assert_byte_pointer_size('')
assert_cursor(3)
assert_cursor_max(3)
input_keys("\C-[[A\C-[[A")
assert_line('abc')
assert_byte_pointer_size('')
assert_cursor(4) …
```
> Fix history navigation in vi_insert mode

- lib/reline/ansi.rb
Pasting multilines at starting up, the pasted input is truncated.
```
irb(main):001:1* def foo
irb(main):002:0> end
=> :foo
def bar
irb(main):003:1* def bar
irb(main):004:1*   [<= no end]
```
> Get rid of `IO.select` to fix multiline paste

- .github/workflows/windows.yml
Use cmd instead of new default shell for `call`.
https://github.blog/changelog/2019-10-17-github-actions-default-shell-on-windows-runners-is-changing-to-powershell/
> Add `shell: cmd`

- lib/reline.rb
Ruby 2.7 deprecates taint and it no longer has an effect.
> Only taint on Ruby <2.7

- lib/reline.rb
- test/reline/test_reline.rb
* `Reline#readline` and `Reline#readmultiline` to `private`
* (`Reline.readline` and `Reline.readmultiline` to `module_function`)
1. `include Reline`
2. call `#readline` with receiver.
```ruby
class X
include Reline
end
x = X.new
x.readline
```
```ruby
require "reline"
class X
include Reline
end
x = X.new
x.instance_eval { readline }
x.readline
```
```ruby
require "reline"
class X
include Reline
end
x = X.new
x.instance_eval { readline }
x.readline
```
* `Readline#readline` is `private`
* (`Readline.readline` is `module_function`)
* I think `Reline` needs to be compatible with `Readline`
* `readmultiline` also needs to follow `readline`
```ruby
require "readline"
class X
include Readline
end
x = X.new
x.instance_eval { readline }
x.readline
```
> Reline#readline and Reline#readmultiline to private.

- lib/reline/ansi.rb
`stty` called in `Reline::ANSI.deprep` command shows the following error message on macOS Apple Terminal, with some settings.
```
$ LANG=C irb
irb(main):001:0>
stty: 'standard input': unable to perform all requested operations
stty: 'standard input': unable to perform all requested operations
```
> Suppress `stty` error on Apple Terminal

- lib/reline/ansi.rb
`<Home>` and `<End>` keys didn't work in Ubuntu 18.04.2 LTS and GNOME 3.28.2.
Add support `<Home>` and `<End>` keys.
> Add support <Home> and <End> keys in Ubuntu 18.04

- lib/reline.rb
- test/reline/test_reline.rb
Change argument `Proc` to `#call` defined object.
This is the same as the behavior of Readline.
```ruby
class DefineCall
def call; end
end
Readline.completion_proc = DefineCall.new
Reline.completion_proc = DefineCall.new
```
```ruby
class DefineCall
def call; end
end
Readline.completion_proc = DefineCall.new
Reline.completion_proc = DefineCall.new
```
* `Reline.completion_proc=`
* `Reline.output_modifier_proc=`
* `Reline.prompt_proc=`
* `Reline.auto_indent_proc=`
* `Reline.dig_perfect_match_proc=`
> Change argument `Proc` to `#call` defined object

- .github/workflows/ubuntu-rvm-with-irb.yml
This closes https://github.com/ruby/reline/pull/76.
> Stop using "bundle exec" for "rake build" and "rake install"

- lib/reline/ansi.rb
Including dsusp, lnext, and so on.
> Disable any implementation-defined special control characters

- .github/workflows/macos.yml
- .github/workflows/ubuntu-rvm-with-irb.yml
- .github/workflows/ubuntu-rvm.yml
- .github/workflows/ubuntu.yml
- .github/workflows/windows.yml
- Rakefile
- download-test_readline.ps1
This PR only affects CI.
1. Rework Windows CI -
1.1 change script that copies ruby/ruby files from a .bat script to a .ps1 script (PowerShell)
1.2 rename readline.so file
1.3 use an 'action' that installs current Rubies, versus the old Rubies on Actions.
1.4 move master/trunk testing to GitHub Actions ('9.9.x')
2. Allow CI to run in forks on branches other than 'master'
3. Split ci-test and test in Rakefile and workflows
Notes:
4. Windows Rubies 2.5 & 2.6 contain a readline.so file, but do not contain the dll they need to load.
5. Left AppVeyor CI as is.
6. To allow Ruby master to always work, it is versioned as '9.9.x' in the workflow matrix, and installed to the 'C:/Ruby99-x64' folder.  When 2.7.0 release is available, I'll update the 'action'.
> Update CI - Windows, forks, etc

- lib/reline/ansi.rb
The old version of cursor_pos discards the input buffer, which made IRB
ignore the input immediately after IRB is invoked.
This change keeps the input before cursor_pos by using ungetc.
> Preserve the input buffer across cursor_pos

- lib/reline/ansi.rb
I often use Ctrl+← and Ctrl+→ as prev_word and prev_word, respectively.  I'm unsure if `ansi.rb` is an appropriate place to put the strokes.
> Support Ctrl+right as em_next_word, and Ctrl+left as ed_prev_word

- lib/reline/ansi.rb
- reline.gemspec
Use `IO#raw` to read a byte in raw mode, instead of calling `stty` command.
> Use IO#raw to read one byte

- lib/reline/ansi.rb
This is a workaround for https://github.com/ruby/irb/issues/50
> Degenerate the terminal size to [$LINES, $COLUMNS] if it is unknown

- lib/reline/line_editor.rb
```console
$ irb --legacy
irb(main):001:0> l[TAB][TAB]
lambda           load             local_variables  loop
```
```console
$ irb
irb(main):001:0> l[TAB][TAB]
local_variables
loop
lambda
load
```
```console
$ irb
irb(main):001:0> l[TAB][TAB]
lambda
load
local_variables
loop
```
> Sort completion list

- .github/workflows/ubuntu-rvm-with-irb.yml
- .github/workflows/ubuntu-rvm-with-readline.yml
- .github/workflows/ubuntu-rvm.yml
GitHub Actions uses RVM binary packages of Travis CI. The packages don't contain ruby-head on Ubuntu 18.04 (ubuntu-latest). Therefore, change the container to Ubuntu 16.04 as a workaround.
> Use Ubuntu 16.04 on GitHub Actions

- lib/reline/windows.rb
I mistook `Right` and `Bottom`.
This fixes https://github.com/ruby/reline/issues/109.
> Fix Reline::Windows#scroll_down

- lib/reline/ansi.rb
- lib/reline/general_io.rb
- lib/reline/line_editor.rb
- lib/reline/windows.rb
A newline is automatically inserted if a character is rendered at eol on Windows command prompt.
This fixes https://github.com/ruby/reline/issues/110.
> Bypass cursor down when a char is rendered at eol on Windows

- lib/reline.rb
- lib/reline/ansi.rb
- lib/reline/line_editor.rb
- lib/reline/windows.rb
`IO#print` always adds a string of `$\` automatically.
> Use IO#write instead of IO#print

- download-test_readline.rb
$ ruby -wc download-test_readline.rb
download-test_readline.rb:50: warning: assigned but unused variable - done
Syntax OK
> Fix a warning and simplify the loop

- lib/reline/config.rb
- test/reline/test_config.rb
In the XDG Specification, if ~/.config/readline/inputrc exists, then ~/.inputrc should not be read, but for compatibility with GNU Readline, if ~/.inputrc exists, then it is given priority.
> Support XDG_CONFIG_HOME

- lib/reline/config.rb
- test/reline/test_config.rb
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
> All paths set in these environment variables must be absolute.  If an implementation encounters a relative path in any of these variables it should consider the path invalid and ignore it.
> Ignore non-absolute XDG_CONFIG_HOME

- lib/reline/config.rb
- lib/reline/history.rb
- test/reline/test_history.rb
* Added new items to history are dropped if history_size is zero
* Negative history_size means unlimited
* Unlimited is default
This fixes https://github.com/ruby/reline/issues/138.
> Fix history_size behaviours

- bin/multiline_repl
- lib/reline.rb
- lib/reline/ansi.rb
Catch `Errno::EIO` what will be occurred if the console terminates I/O before Reline finishes rendering.
> Check Errno::EIO

- lib/reline.rb
- lib/reline/config.rb
- lib/reline/line_editor.rb
- test/reline/yamatanooroti/test_rendering.rb
This Pull Request is based on https://github.com/ruby/reline/pull/148 and the author of the commit is @jethrodaniel.
I enhanced the original commit by some points:
- Support "on/off" by `show-mode-in-prompt`
- Use a better way to fix complicated rendering and reading config steps
- Add tests by [yamatanooroti gem](https://rubygems.org/gems/yamatanooroti)
- And other small fixes
Previously, only internal state testing was done, but it wasn't possible to test for prompts because prompts are generated in the final rendering step. I developed yamatanooroti gem to test the rendering steps but it had some bugs, so [yamatanooroti test](https://github.com/ruby/reline/blob/d07601d54e08735c0a4c2ca8080f1d99cb507664/.github/workflows/reline.yml#L110-L111) was failing in CI. I fixed them:
- …
> Support mode icon

- reline.gemspec
It is better to use SPDX ID for license field:
https://guides.rubygems.org/specification-reference/#license=
ref: https://spdx.org/licenses/Ruby.html
> Use the standard SPDX ID for license in gemspec

- lib/reline/windows.rb
I like ctrl+L, but not work with RubyInstaller for Windows 2.7.1-1.
```irb(main):001:0> Traceback (most recent call last):
31: from ./irb:23:in `<main>'
30: from ./irb:23:in `load'
29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/irb-1.2.3/exe/irb:11:in `<top (required)>'
28: from C:/Ruby27-x64/lib/ruby/2.7.0/irb.rb:399:in `start'
27: from C:/Ruby27-x64/lib/ruby/2.7.0/irb.rb:470:in `run'
26: from C:/Ruby27-x64/lib/ruby/2.7.0/irb.rb:470:in `catch'
25: from C:/Ruby27-x64/lib/ruby/2.7.0/irb.rb:471:in `block in run'
24: from C:/Ruby27-x64/lib/ruby/2.7.0/irb.rb:536:in `eval_input'
23: from C:/Ruby27-x64/lib/ruby/2.7.0/irb/ruby-lex.rb:134:in `each_top_level_statement'
22: from C:/Ruby27-x64/lib/ruby/2.7.0/irb/ruby-lex.rb:134:in `catch'
21: from C:/Ruby27-x64/lib/ruby/2.7.0/irb/ruby-lex.rb:135:in …
```
> IRB cause NoMethodError with clrl+L on windows.

- lib/reline/ansi.rb
The nil means there is nothing in the buffer in some systems. Incidentally, `Errno::EIO` is raised if the I/O is closed.
> Skip the nil obtained from getc

- lib/reline/line_editor.rb
When the cursor is at the end of the line and erases characters after the cursor, some terminals delete the character at the cursor position.
> Stop erasing chars after the cursor at eol

- lib/reline/line_editor.rb
Workaround for https://github.com/ruby/reline/issues/165.
> Stop using chomp option of lines method

- lib/reline/ansi.rb
This closes https://github.com/ruby/irb/issues/91.
> Support for word movement escape sequences in iTerm2

- test/reline/yamatanooroti/test_rendering.rb
A newline is automatically inserted if a character is rendered at eol on command prompt.
> Bypass newline insertion at eol on command prompt

- lib/reline.rb
- lib/reline/ansi.rb
- lib/reline/general_io.rb
- lib/reline/line_editor.rb
- lib/reline/windows.rb
IRB uses Reline's 3 dynamic real-time callbacks with calling Ripper; `output_modifier_proc`, `prompt_proc`, and `auto_indent_proc`. These processing times make the paste time too long.
Before:
Needs 16 seconds to paste the code of ruby/reline#74.
After:
About 2 seconds.
ref. https://github.com/ruby/irb/issues/43, https://github.com/ruby/reline/pull/184
> Suppress callbacks in pasting

- lib/reline/line_editor.rb
```ruby
[{"_id"=>"5f9072a4589a06d2d74b6028",
"index"=>0,
"guid"=>"6b3051e2-dbc7-4537-bdb9-6cd7bb5358a7",
"isActive"=>true,
"balance"=>"$1,442.84",
"picture"=>"http://placehold.it/32x32",
"age"=>34,
"eyeColor"=>"blue",
"name"=>{"first"=>"Ward", "last"=>"Levy"},
"company"=>"HYPLEX",
"email"=>"ward.levy@hyplex.us",
"phone"=>"+1 (867) 568-3319",
"address"=>"867 Cobek Court, Clara, Maryland, 3254",
"about"=>
"Exercitation eu ex aliqua sit. Pariatur aliquip incididunt sint id non consectetur ullamco Lorem ea mollit duis amet sint labore. Commodo laborum labore commodo officia in cillum adipisicing esse excepteur cupidatat adipisicing ut. Non esse incididunt voluptate aliquip cillum eu aute duis laboris sit et. Amet enim …
```
> Continuous insertion buffering

- lib/reline/line_editor.rb
- test/reline/test_key_actor_emacs.rb
This closes https://github.com/ruby/reline/issues/193.
> Skip em_exchange_mark without mark

- lib/reline/key_actor/vi_command.rb
This closes https://github.com/ruby/reline/issues/192.
> Backspace and C-h should be unassigned on vi command mode

- lib/reline/line_editor.rb
- test/reline/test_key_actor_vi.rb
The proc variable will be used later so the instance variable will be changes.
This closes https://github.com/ruby/reline/issues/188.
> Keep operator proc as a local variable in the scope

- lib/reline/line_editor.rb
- test/reline/test_key_actor_vi.rb
This closes https://github.com/ruby/reline/issues/191.
> Unimplemented vi command should be no-op

- lib/reline/line_editor.rb
- test/reline/test_key_actor_vi.rb
This closes https://github.com/ruby/reline/issues/190.
> Implement vi_yank

- lib/reline/line_editor.rb
- test/reline/test_key_actor_vi.rb
This closes https://github.com/ruby/reline/issues/189.
> Motions e, E, t, f should include a char on cursor if follows operator

- lib/reline/unicode.rb
- test/reline/test_unicode.rb
Fix #174.
This is because [`Reline.ambiguous_width` case was removed here](https://github.com/ruby/reline/commit/e36f6c070784b972955f490f71d3af9df125b8f5#diff-a29767a3bb4f901d7224743024c7734d625b5b2c3e62a892140d93c27866e218L84). (Thanks @ima1zumi :)
> Fix crash to input `é`

- lib/reline/line_editor.rb
- test/reline/test_key_actor_vi.rb
Key strokes, vi arg, operator, and motion should be treated as operator, vi arg, and motion.
> Key strokes like 2dl should behave d2l

- lib/reline/unicode.rb
```ruby
[{"_id"=>"5f9072a4589a06d2d74b6028",
"index"=>0,
"guid"=>"6b3051e2-dbc7-4537-bdb9-6cd7bb5358a7",
"isActive"=>true,
"balance"=>"$1,442.84",
"picture"=>"http://placehold.it/32x32",
"age"=>34,
"eyeColor"=>"blue",
"name"=>{"first"=>"Ward", "last"=>"Levy"},
"company"=>"HYPLEX",
"email"=>"ward.levy@hyplex.us",
"phone"=>"+1 (867) 568-3319",
"address"=>"867 Cobek Court, Clara, Maryland, 3254",
"about"=>
"Exercitation eu ex aliqua sit. Pariatur aliquip incididunt sint id non consectetur ullamco Lorem ea mollit duis amet sint labore. Commodo laborum labore commodo officia in cillum adipisicing esse excepteur cupidatat adipisicing ut. Non esse incididunt voluptate aliquip cillum eu aute duis laboris sit et. Amet enim …
```
> Optimize ASCII character width calculation

- lib/reline/ansi.rb
When running irb 1.2.1 (2019-12-24) with frozen-string-literal enabled, it crashes in reline with `can't modify frozen String (FrozenError)`
Steps to reproduce: 
`RUBYOPT="--enable-frozen-string-literal" irb`
> Cope with frozen-string-literal

- lib/reline/line_editor.rb
- test/reline/test_key_actor_emacs.rb
refs: https://github.com/ruby/reline/issues/178
Fixed an issue that the cursor position would wrong when input the including Zero-width joiner character. 
For example: family emoji 👨‍👩‍👧‍👧 .
> Fix breaking to input Emoji with ZWJ.

- lib/reline/config.rb
- lib/reline/line_editor.rb
- test/reline/test_key_actor_emacs.rb
- test/reline/yamatanooroti/test_rendering.rb
This closes https://github.com/ruby/reline/issues/81.
> Support isearch-terminators

- lib/reline.rb
- test/reline/test_unicode.rb
Fix : https://bugs.ruby-lang.org/issues/17405
steps to reproduce a bug
`test.rb`
```ruby
require "reline"
p Reline::Unicode.calculate_width("√")
```
```
❯ ruby -v           
ruby 3.0.0rc1 (2020-12-20 master 8680ae9cbd) [x86_64-darwin19]
❯ ruby test.rb
/Users/mi/.rbenv/versions/3.0.0-rc1/lib/ruby/3.0.0/reline/unicode.rb:136:in `+': nil can't be coerced into Integer (TypeError)
from /Users/mi/.rbenv/versions/3.0.0-rc1/lib/ruby/3.0.0/reline/unicode.rb:136:in `block in calculate_width'
from /Users/mi/.rbenv/versions/3.0.0-rc1/lib/ruby/3.0.0/reline/unicode.rb:126:in `scan'
from /Users/mi/.rbenv/versions/3.0.0-rc1/lib/ruby/3.0.0/reline/unicode.rb:126:in `calculate_width'
from ./reline/test.rb:5:in `<main>'
```
Thanks @osyo-manga 😄
> Fixed an exception occurred when ambiguous width character was passed to `#calculate_width` [Bug #17405]

- lib/reline/line_editor.rb
- test/reline/yamatanooroti/test_rendering.rb
This fixes https://github.com/ruby/reline/issues/226.
> Discard prompt cache by changing mode icon

- lib/reline/line_editor.rb
- test/reline/test_key_actor_vi.rb
> Use #bytesize for vi_replace_char

- lib/reline/line_editor.rb
- test/reline/yamatanooroti/test_rendering.rb
This fixes ruby/reline#236 and ruby/reline#239.
> Update cursor correctly when just cursor moving

- bin/multiline_repl
- bin/termination_checker.rb
- lib/reline/line_editor.rb
- test/reline/yamatanooroti/test_rendering.rb
ref. https://github.com/ruby/reline/pull/242
> Suppress crashing when broken information comes from callbacks

- lib/reline/line_editor.rb
- test/reline/helper.rb
- test/reline/test_key_actor_emacs.rb
The current line was being handled incorrectly when displaying the hit history, so it has been fixed to be correct.
> Handle ed_search_{prev,next}_history in multiline correctly

- lib/reline/line_editor.rb
- test/reline/test_key_actor_vi.rb
> Move the cursor correctly when deleting at eol

- lib/reline/line_editor.rb
The behavior of automatically moving the cursor to the next line when displaying a char at the eol on Windows suddenly disappeared.
ref. https://twitter.com/nagisakaworu17/status/1347802370357354498
> Support for change in Windows-specific behavior at eol

- lib/reline/windows.rb
ref. https://twitter.com/nagisakaworu17/status/1347802370357354498
> Reline::Windows.erase_after_cursor erases attributes too

- lib/reline.rb
- lib/reline/line_editor.rb
Because it's too slow.
```ruby
def each_top_level_statement
initialize_input
catch(:TERM_INPUT) do
loop do
begin
prompt
unless l = lex
throw :TERM_INPUT if @line == ''
else
@line_no += l.count("\n")
next if l == "\n"
@line.concat l
if @code_block_open or @ltype or @continue or @indent > 0
next
end
end
if @line != "\n"
@line.force_encoding(@io.encoding)
yield @line, @exp_line_no
end
break if @io.eof?
@line = ''
@exp_line_no = @line_no
@indent = 0
rescue TerminateLineInput
initialize_input
prompt
end
end
end
end
puts "Duration: #{Time.now - start} seconds"
```
0.22sec -> 0.14sec
This fixes https://github.com/ruby/irb/issues/176.
> Cache pasting state in processing a key

- lib/reline/line_editor.rb
On Unix-like OSes, logs prior to the screen are not editable. When the code is higher than the screen, the code is only shown on the screen until input is finished, but when it is finished, all lines are outputted.
This fixes https://github.com/ruby/irb/issues/175.
> Show all lines higher than screen when finished

- lib/reline/unicode.rb
- test/reline/test_key_actor_emacs.rb
> Return 1 when char width not found

- lib/reline/line_editor.rb
Starting irb and type dollar `$` causes a crash.
The cause is that `prompt` is nil, because `prompt_list` is empty. 
I'm offering this fix. There is no test coverage, for which I apologise. I'd be happy to collaborate with someone who knows the repo better.
> Avoid tripping over nil prompt

- lib/reline/line_editor.rb
I confirmed that libvterm supports only which are UTF-8, US ASCII, UK, and DEC graphics by reading source code, so can't test this patch by yamatanoorogi gem through vterm gem for now.
This fixes ruby/irb#190.
> Use UTF-8 only for width calc, rest uses original encoding

- lib/reline/line_editor.rb
- lib/reline/windows.rb
This patch solves the problem that `rake test_yamatanooroti` (after `gem install yamatanooroti`) fails the test in Ruby 2.7 on Windows.
Thank you so much, @YO4!
This closes https://github.com/ruby/reline/issues/265.
> Add windows getconsolemode

- lib/reline/windows.rb
use double quotes to properly convert the \000 escape sequence.
> fix Reline::Windows.getconsolemode buffer

- .github/workflows/reline.yml
Adds Ruby 3.0 to the versions which are explicitly tested against in the CI workflow.
I noticed that the `reline` job has more versions listed than the `vterm-yamatanooroti` one. The latter is missing ruby 2.5. I am not sure if that is intentional or not but I made this PR with the intention of making the smallest change possible and so left everything else as it is.
Closes #237
> Add Ruby 3.0 to list of versions in CI workflow

- lib/reline.rb
- lib/reline/ansi.rb
- lib/reline/config.rb
- lib/reline/general_io.rb
- lib/reline/key_actor/base.rb
- lib/reline/windows.rb
- test/reline/test_config.rb
This closes https://github.com/ruby/reline/issues/33.
> Separate keystrokes each editing mode

- Gemfile
- reline.gemspec
As expressions in a gemspec file are evaluated at the build time, but not the run time, the conditional in the gemspec will not work as intended.
> Moved development dependencies to Gemfile

- lib/reline/config.rb
- test/reline/test_config.rb
This change ensures we use `Reline::IOGate`'s `encoding` when converting
characters from their integer values.
This fixes an issue that may occur if you have UTF characters in your
`.inputrc`, but your default encoding isn't set.
For example:
```
> 127864.ord.chr
RangeError: 127864 out of char range
from (pry):1:in `chr'
> Reline::IOGate.encoding
=> #<Encoding:UTF-8>
> 127864.ord.chr(Reline::IOGate.encoding)
=> "🍸"
```
> ensure reline's encoding is used when reading inputrc character values

- lib/reline/config.rb
- lib/reline/general_io.rb
- test/reline/helper.rb
- test/reline/test_config.rb
- test/reline/test_history.rb
- test/reline/test_reline.rb
In Japan, so many programmers used EUC-JP to write text files that contain Japanese. Many .inputrc files which contain EUC-JP are still being copied and used. This commit supports the whole encoding of what user set including UTF-8.
ref. https://github.com/ruby/reline/pull/280
> The config file must accept any character encoding

- .github/workflows/reline.yml
The 'readline' jobs weren't running.  if one views a run thru the ['Actions'](https://github.com/ruby/reline/actions) tab, you'll see the jobs won't run because the runner is confused as to the OS...
Note:
The '-latest' suffix for the OS designation may change what version it refers to.  I've changed a few repos to using just the numeric suffix, so `ubuntu-latest` would become `ubuntu-20.04`.
> Fix GitHub Actions

- lib/reline.rb
- lib/reline/general_io.rb
This fixes an error when output is redirected:
```
$ run_ruby -rreline -e '$stderr.puts Reline::Unicode.calculate_width("\u221a").inspect' </dev/null >/dev/null
/home/jeremy/tmp/ruby/lib/reline/ansi.rb:189:in `raw': Operation not supported by device (Errno::ENODEV)
```
The @@encoding -> defined?(@@encoding) changes is necessary because
without that part of the commit, the following error would be raised
by the above command:
```
/home/jeremy/tmp/reline/lib/reline/general_io.rb:10:in `encoding': uninitialized class variable @@encoding in Reline::GeneralIO (NameError)
```
Problem reported and initial patch for Windows provided by
Richard Sharman.
I tested this only on OpenBSD, but hopefully it works for other
operating systems.
Fixes [Bug #17493]
> Fix Reline::Unicode.calculate_width when input is not a TTY

- Gemfile
Remove generated comment.
The github git_source exists that way in Bundler 2, so it is available if we want to use it later.
> Gemfile: Drop unused github git_source alias

- README.md
Added sample code for `Reline.readmultiline`.
In my opinion, Usage would be as short as possible, so it is better to see `test/reline/yamatanooroti/multiline_repl` for details.
If you have any concerns, please let me know. :)
sample code's executable example:
```bash
❯ ruby example.rb
prompt> irb
prompt> reline
prompt> end
You entered:
irb
reline
end
prompt>
^C
```
thanks @osyo-manga 😄
> Add usage for README.md

- test/reline/test_key_actor_emacs.rb
For ruby/ruby repository's  AppVeyor CI (Windows environment), `Reline::IOGate.encoding` will be changed from `UTF-8` to `Windows-31J` after the test is run.
So, when `test/reline/test_key_actor_emacs.rb` is loaded, `Reline::IOGate.encoding == Encoding::UTF_8` will be `true`,
but at the time of test execution, `Reline::IOGate.encoding` is `Windows-31J`.
For this reason, I changed the test method to check `Reline::IOGate.encoding` in the test method.
> Fix failed test

- lib/reline/windows.rb
- test/reline/yamatanooroti/test_rendering.rb
Fixes #298
The test fails on Ubuntu, so that it's omitted on non-Windows. Obviously the meta key handling is different there.
> Windows cmd: Don't type anything when pressing ALT keys alone

- lib/reline/windows.rb
The yamatanooroti gem can't emulate numpad key pressing...
This fixes https://github.com/ruby/reline/issues/302.
> Support Enter key of numpad on Windows

- lib/reline/terminfo.rb
OpenBSD doesn't support tiparm, only tparm.  I'm not sure if the
two are compatible, but this at least this allows me to run irb
on OpenBSD.
> Fix reline on OpenBSD

- lib/reline/windows.rb
- test/reline/windows/test_key_event_record.rb
PR to fix #309.
It assumes that Ctrl+Enter functions the same way as Shift+Enter.
I refactored the `process_key_event` method so it's easier to specify key events.
> Fix Ctrl+Enter key in Windows

- lib/reline/ansi.rb
- test/reline/yamatanooroti/termination_checker.rb
- test/reline/yamatanooroti/test_rendering.rb
There used to be a process that did not want to be interrupted by SIGINT, so it was trapped, but that process is no longer there.
> Remove interrupt avoidance

- lib/reline/config.rb
Fix #319.
When `ENV["HOME"] = "foo"` on irb, an exception is raised when retrieving the path of `.inputrc`.
Memoize the path of `.inputrc` and don't get the path after the second time.
> Memoize path of `.inputrc` 

- download-test_readline.rb
- lib/reline/key_stroke.rb
@jhawthorn said, "this will make Ruby's integer comparisons slower globally." It looks like "binding.irb" is going to cause serious
problems in Rails applications.
> Use expanded method definitions instead of refinements

- lib/reline/ansi.rb
This fixes https://github.com/ruby/reline/issues/352.
> Support S-Tab to move up completion cursor in vi-mode on Unix

- lib/reline/line_editor.rb
This operation is mentioned and bound to `^U` in both `vi_command.rb`
and `vi_insert.rb`, but there is no definition of it.
Both Vi and Emacs use the same keystroke to do the same behavior, so
I've chosen to use `alias_method` to make the implementation small,
rather than duplicating the method and re-implementing it.
> Implement vi_kill_line_prev

- lib/reline/line_editor.rb
- test/reline/test_key_actor_emacs.rb
The vi mode can handle "argument number" before an operator or a motion, such as, "3x" (equals "xxx"), and "3l" (equals "lll"). In the emacs mode, GNU Readline can handle argument number with meta key, like "Meta+3 x" (equals "xxx").
> Support ed_argument_digit by M+num

- lib/reline/ansi.rb
- lib/reline/line_editor.rb
The current SIGWINCH handler is too large, so it causes Segmentation fault or ThreadError when resizing.
Fix https://github.com/ruby/irb/issues/282
> Simplify SIGWINCH handler to avoid aborting when resizing.

- lib/reline/line_editor.rb
- test/reline/yamatanooroti/test_rendering.rb
When just after pasting, should rerender prompt if an argument is provided.
> Rerender whole buffer when arg editing is finished

- lib/reline/line_editor.rb
- test/reline/yamatanooroti/multiline_repl
- test/reline/yamatanooroti/test_rendering.rb
This fixes https://github.com/ruby/reline/issues/342 and https://github.com/ruby/reline/issues/349.
> Re-calc the scroll pos when the content in dialog is shortened

- lib/reline/windows.rb
This fixes https://github.com/ruby/irb/issues/260.
> Use default background color to erase on Windows

- lib/reline/line_editor.rb
- test/reline/yamatanooroti/multiline_repl
- test/reline/yamatanooroti/test_rendering.rb
fix https://github.com/ruby/irb/issues/308
This bug occurred when `dialog.width - calculate_width(s, true)` was negative.
When `dialog.width` is shorter than `old_dialog.width`, it calculates how much padding it has to do. However, there are cases where `s` is longer than `dialog.width`, as in the issue. In that case, `padding_space_with_escape_sequences` will crash.
Here, `old_dialog.width` is longer than `dialog.width`, so I changed the padding width to `old_dialog.width - dialog.width`.
> Correct padding space calculation

- lib/reline/ansi.rb
It's already checked in the previous line.
> No need to check `x > 0`

- lib/reline/windows.rb
fix #300
Recheck consolemode during keyboard idle time.
getconsolemode runs 13k i/s (benchmark-ips) on my machine. so, fewer check gains paste speed (hopefully).
> windows: detect consolemode change

- lib/reline/windows.rb
fix #350
```
irb(main):001:0> puts "🍣"*5
🍣🍣🍣🍣🍣
=> nil
```
> windows: support input surrogate paird codepoint

- lib/reline/windows.rb
Reline::Windows.in_pasting not working, this patch resolve it.
paste #74 code between 
```
t = Time.now
p (Time.now - t) * 1000
```
shows 2700msec -> 410msec.
074e407c62e6615c577e77fdf9328d41367015fb and eb3ef7af98ed44df7170d3247410a400725d08a9 both required.
Either one patch works less/none.
ref. #186
> improve windows paste speed

- lib/reline/config.rb
- lib/reline/key_stroke.rb
- test/reline/test_config.rb
- test/reline/yamatanooroti/test_rendering.rb
fix #357
When using 8-bit characters, it is better not to use `compress_meta_key`.
I believe not to use `compress_meta_key` unless `set convert-meta on` is written in the `.inputrc`.
The following is a quote from tmtm's comments.
> The behavior of this compress_meta_key method is similar to the behavior of convert-meta=on in readline, but readline turns off convert-meta if the locale contains 8bit characters.
> In readline(3):
> convert-meta (On)
> If set to On, readline will convert characters with the eighth
> bit set to an ASCII key sequence by stripping the eighth bit and
> prefixing it with an escape character (in effect, using escape
> as the meta prefix). The default is On, but readline will set
> it to Off if the locale contains eight-bit characters.
Co-authored-by: TOMITA …
> Execute compress_meta_key if convert_meta is on

- lib/reline/ansi.rb
- lib/reline/general_io.rb
The fiber scheduler does not handle `IO#select` and for one IO there is no point to use it. Using `IO#wait_readable` is the preferred approach as it works both with and without the fiber scheduler.
> Prefer wait_readable for fiber scheduler.

- lib/reline/line_editor.rb
- test/reline/yamatanooroti/test_rendering.rb
The number of lines below the cursor position was known by `@rest_height` alone, but the problem was caused by adding `lower_space`. Remove `lower_space` as it is unnecessary.
This fixes https://github.com/ruby/reline/issues/391.
> Remove unnecessary variables, `lower_space`

- reline.gemspec
When merged to ruby/ruby, reline.gemspec file is located under lib/reline, as the same as reline/version.rb.
That is the latter path relative from the former differs from the ruby/reline case, and the reline/version.rb in the default load path will be loaded.
Try `require_relative` not to load unexpected files.
> Load correct version.rb from gemspec

- lib/reline/windows.rb
improve reline/windows.rb
- In Windows Terminal, scroll with API does not store backbuffer.
- Newer Windows console does smart screen clearing with \e[2J.
This patch change scroll_down() and clear_screen() to use escape sequences.
Brings modern usability for windows irb users :-)
> Windows support modern terminal

- lib/reline.rb
- lib/reline/ansi.rb
- lib/reline/line_editor.rb
In some tests, the `LineEditor#reset` method is always called, but doesn't need to set the signal handlers there, so cuts it out to a separate method.
> Split off set_signal_handler method

- lib/reline.rb
- lib/reline/line_editor.rb
This fixes https://github.com/ruby/reline/issues/351.
> Finalize when exception occurred

- lib/reline/line_editor.rb
- lib/reline/unicode.rb
- test/reline/test_key_actor_emacs.rb
When a halfwidth character is followed by a halfwidth dakuten or a halfwidth handakuten character, it should be treated as a single grapheme. So, even if the number of graphemes doesn't change owing to character merging, the character width may increase.
This fixes https://github.com/ruby/reline/issues/405.
> Character merging may increase the character width

- test/reline/helper.rb
- test/reline/test_key_actor_emacs.rb
The method "input_keys" in test/reline/helper.rb handles a single-byte
and 8-bit charater as an input with the meta key.
However, "test_halfwidth_kana_width_dakuten" in test/reline/test_key_actor_emacs.rb
uses a string that contains "hankaku" characters.
A "hankaku" character is not with the meta key, but it is a single-byte
and 8-bit character on Windows-31J encoding, which confused "input_keys"
method. This caused the following error.
https://ci.appveyor.com/project/ruby/ruby/builds/41997092/job/ejm77qxgvnlpdwvg
```
1) Failure:
Reline::KeyActor::Emacs::Test#test_halfwidth_kana_width_dakuten [C:/projects/ruby/test/reline/test_key_actor_emacs.rb:2311]:
<"\xB6\xDE\xB7\xDE\xB9\xDE\xBA\xDE" (#<Encoding:Windows-31J>)> expected but was
<"\e^\e^\e^\e:\e^" (#<Encoding:Windows-31J>)> in <Terminal …
```
> Fix test input_keys to handle "hankaku" characters correctly on Windows

- test/reline/test_reline.rb
- test/reline/test_terminfo.rb
`skip` is minitest methods. I hope to migrate it to `omit` provided by `test-unit`
> Use omit instead of skip

- lib/reline/key_actor/emacs.rb
- test/reline/test_key_actor_emacs.rb
fix https://github.com/ruby/reline/issues/415
The kill-line was called when C-u was entered, so it is now called unix-line-discard.
In readline(3):
> unix-line-discard (C-u)
>               Kill backward from point to the beginning of the line.
>               The killed text is saved on the kill-ring.
> Use unix_line_discard when Ctrl-u is entered

- lib/reline/windows.rb
Sorry, my patch b61bc43374931dcc2a92325b7a661d7d30fb459d break scrolling.
In Windows Terminal, scrolling shows strange behavior(cursor jumping).
In cmd.exe, this comes in last line of screen buffer. 
I missed this because of using cmd.exe with long screen buffer.
> windows fix scroll

- .github/workflows/reline.yml
Added `--pre` because `gem install irb -f` can't install the prerelease version of irb.
> Use prerelease version of irb on CI

- Gemfile
ruby 2.7 bundles irb 1.2.6
test/relline/yamatanooroti/termination_checker.rb, RubyLex.ripper_lex_without_warning() needs irb >= 1.3.6
> test_yamatanooroti on ruby 2.7 needs irb>=1.3.6

- test/reline/yamatanooroti/test_rendering.rb
Because of console geometry, SetConsoleScreenBufferSize() fails in yamatanooroti/windows.rb
SetConsoleScreenBufferSize() fails at too narrow console size (in pixel).
Bigger font resolv this, but screen height limit is other probrem.
1080lines screen needs this patch, 1440lines screen not
With this patch and yamatanootori head,
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32] passed test_yamatanooroti with
```
Finished in 315.1460539 seconds.
------------------------------------------------------------------------------------------------------------------------
76 tests, 74 assertions, 0 failures, 0 errors, 0 pendings, 2 omissions, 0 notifications
100% passed
------------------------------------------------------------------------------------------------------------------------ …
```
> windows: test_yamatanooroti fix

- lib/reline/terminfo.rb
Solaris requires that the pointer errret_int is alined to an integer,
however, with VWA, strings are no longer aligned to an integer, so use a
Fiddle::Pointer with a malloc'd region instead.
> Fix reline on Solaris

- lib/reline/terminfo.rb
If a top-level `VERSION` constant exists, or if a module containing a `VERSION` constant is included into the top-level scope, then `Fiddle.const_defined?(:VERSION)` will erroneously return true when `RUBY_VERSION < '3.0.0'`.
> Ignore global constants when checking if Fiddle::VERSION exists

- lib/reline/windows.rb
On European keyboards.
This fixes https://github.com/ruby/irb/issues/331.
ref.
- https://devblogs.microsoft.com/oldnewthing/20040329-00/?p=40003
- https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-advanced
> The AltGr behaves exactly the same as Ctrl+Alt

- lib/reline/config.rb
- test/reline/test_config.rb
The existing implementation, given the below .inputrc, erroneously creates a `C-v` key binding:
set keymap emacs-ctlx
"\C-v": "[C-x C-v was pressed]"
This fixes it to instead create a `C-x C-v` keybinding.
> Fix support for emacs-ctlx and emacs-meta keymaps

- lib/reline/terminfo.rb
This maybe isn't probably isn't the best approach, but it should allow
`Fiddle::Terminfo.curses_dl` to work.  I documented more details about
this in an issue on fiddle: https://github.com/ruby/fiddle/issues/107
It is probably better to deal with it there.  But this workaround is
simpler.
FYI: `reline` itself seems to be working just fine for me _without_
loading ncurses.  But I wanted to be able to use `Reline::Terminfo` for
my own projects. :)
> Workaround libncurses.so as a linker script

- lib/reline.rb
It sent the char to check even to non-tty, e.g., pipe.
This causes `unknown command: "\xE2\x96\xBDstart ` warnings on ruby's parallel test on Windows, where non-standard FDs cannot be passed to child processes.
> Check the ambiguous char width only on tty

- lib/reline.rb
- lib/reline/config.rb
- test/reline/test_config.rb
- test/reline/test_reline.rb
"Pointer" is not what we usually use to describe a selected item.
"Highlight" is a more common word for the scenario so we should use it instead.
> Rename dialog_pointer_* to dialog_highlight_*

- lib/reline/line_editor.rb
The variable ``str`` is not used after this point, making the string operation ``str += ''`` unnecessary.
> Remove loose operation in Dialog#render_each_dialog

- lib/reline.rb
- test/reline/test_reline.rb
The "dumb" terminal is considered only on MSys tty now.
However, the `TERM` feature has been used on many Unix-like systems for decades, not MSys specific.
> Support dumb terminal

- lib/reline/ansi.rb
- Obviously, `tim` is a typo for `time`. see https://github.com/ruby/ruby/blob/v3_1_3/ext/io/console/console.c#L1637
- This didn't cause an ArgumentError because IO#raw is implemented in C and it doesn't check the keyword
- Also, this typo works well because `tim: 0` is not inconsistent with the `time`'s default value `0`. see https://github.com/ruby/ruby/blob/v3_1_3/ext/io/console/console.c#L147
- This typo doesn't produce any problems for now, though I think it'd be better to fix it just in case for the future
> Fix misuse of kwarg in IO#raw

- lib/reline.rb
- lib/reline/config.rb
- test/reline/test_config.rb
- test/reline/test_reline.rb
These APIs/configs are not approved by the Ruby core, so they can't be released to the public. This means having them in the codebase will block other fixes/features from being released as well.
So this commit removes those exposed interfaces to unblock the release.
Hopefully when https://bugs.ruby-lang.org/issues/18996 is approved we can re-implement better APIs.
([Conclusion about this feature](https://github.com/ruby/dev-meeting-log/blob/master/DevMeeting-2022-12-01.md#feature-18996-proposal-introduce-new-apis-to-reline-for-changing-dialog-ui-colours-st0012) in the 1st Dec dev meeting)
cc @pocari
> Remove unapproved color setting APIs

- test/reline/yamatanooroti/termination_checker.rb
The keyword parameter `:context` of RubyLex#set_input became mandatory due to this commit: https://github.com/ruby/irb/pull/427/files#diff-612b926e42ed78aed1a889ac1944f7d22229b3a489cc08f837a7f75eca3d3399R51
Without my patch, tests that specify "--auto-indent" option in test_yamatanooroti fall into an infinite loop.
This would need more explanation:
- The infinite loop happens in Yamatanooroti::VTermTestCaseModule#sync see: https://github.com/aycabta/yamatanooroti/blob/v0.0.9/lib/yamatanooroti/vterm.rb#L60-L63
- `@pty_output.read_nonblock(1024)` actually returned an exception
- However, this method doesn't anticipate such a situation
- As a result, `startup_message` couldn't be resolved for good and the infinite loop happens
- I think we would eventually have to fix yamatanooroti, though …
> Fix a misparameter of RubyLex#set_input in termination_checker.rb

- .github/workflows/reline.yml
Currently the `yamatanooroti` tests don't actually run anything on CI ([example](https://github.com/ruby/reline/actions/runs/3692513824/jobs/6251490594)). This is because #480 added `bundle exec`, so the `vterm` gem won't be required without `WITH_VTERM` env set.
This PR fixes the issue.
> Activate yamatanooroti tests with WITH_VTERM=1

- lib/reline/windows.rb
JRuby 9.4.0.0 seems to have introduced a change in case sensitivity in require statements, meaning that an inclusion of `win32api` that previously loaded Win32API.rb no longer works. With this change, the require statement needs to be updated to the correct capitalization of the filename to avoid reline failures in newer versions of JRuby.
This is intended to address #476. I haven't had a chance to test it myself for resolution of the JRuby problem, but will update this request once I have.
EDIT: clarify problem description and apparent cause
> correct Win32API capitalization for JRuby

- lib/reline/ansi.rb
- test/reline/helper.rb
- test/reline/test_ansi_with_terminfo.rb
- test/reline/test_ansi_without_terminfo.rb
This fixes the delete key (delete on pc keyboard; fn+delete on mac keyboard) to work on macOS in Terminal and iTerm2.
~It also fixes the insert, pgup, and pgdn keys to no longer spew out ugly escape codes.~ (do these later in a separate MR)
Helps with issue https://github.com/ruby/irb/issues/330.
> Add key binding for Delete (save Insert, PgUp, PgDn for later)

- lib/reline/line_editor.rb
- test/reline/yamatanooroti/multiline_repl
- test/reline/yamatanooroti/test_rendering.rb
In some case, modified lines was passed to auto_indent_proc.
This pullreq will fix some prompt bug in irb.
```
irb(main):002:1* if 1
irb(main):003:1"   %[
irb(main):004:13>   a a a a
irb(main):006:1"   a a a a
```
> Pass unmodifined lines(that does not include escape sequence) to check_multiline_prompt

- lib/reline/unicode/east_asian_width.rb
Ruby core has updated UCD version based on Unicode 14.0.0.
* [update Unicode Version to 14\.0\.0 and Emoji version to 14\.0 · ruby/ruby@45e0711 · GitHub](https://github.com/ruby/ruby/commit/45e0711f29f9ce65cd34ad14e3af1546ccc7252e)
Following this, I updated Reline's East Asian Width table to Unicode 14.0.0 based.
> Update to Unicode 15.0.0

- .github/workflows/reline.yml
Because the default timeout is 6 hours. Sometimes ci runs until it timeout.
The most recent run time is about 5 minutes, so 30 minutes will be fine.
> Add timeout minutes

- test/reline/yamatanooroti/multiline_repl
- test/reline/yamatanooroti/termination_checker.rb
- test/reline/yamatanooroti/test_rendering.rb
In master, it seems that test_yamatanooroti fails.
```
% bundle exec ruby -Ilib test/reline/yamatanooroti/multiline_repl
Multiline REPL.
/Users/tomoya/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/irb-5c8d3df2df3c/lib/irb/ruby-lex.rb:19:in `initialize': wrong number of arguments (given 0, expected 1) (ArgumentError)
from test/reline/yamatanooroti/multiline_repl:197:in `new'
from test/reline/yamatanooroti/multiline_repl:197:in `<main>'
```
`class TerminationChecker < RubyLex` now needs context in constructor and `multiline_repl` does not work now.
I'm also opening a pull request in irb (https://github.com/ruby/irb/pull/500) that deletes `RubyLex#process_nesting_level` and `RubyLex#process_literal_type` and it will also breaks reline's test.
I think multiline_repl don't need to …
> multiline_repl do not need to depend on RubyLex

- lib/reline/config.rb
A small thing I noticed while reading the source code. Since we're collecting the arguments with a splat, we'll always get an Array, which responds to `any?`, so it's not necessary to check for that.
> Splat is always an Array

- lib/reline/line_editor.rb
- test/reline/yamatanooroti/test_rendering.rb
- Scrollbar is not shown at bottom when I scrolled to bottom
- Pink color is remained in scrollbar area
- Scrollbar sometimes disappears after you scroll or when dialog size change (not shown in the gif below)
- Scrollbar will disappear if contents is very long (not shown in the gif below)
```diff
pointer = dialog.pointer - dialog.scroll_top
+      else
+        dialog.scroll_top = 0
end
```
Resets scroll_top to zero if `dialog.pointer == nil`. It will be nil when `dialog_render_info.contents` changed.
Originally, reset is done at `dialog.scroll_top = dialog.contents.size - height` that I deleted in change2.
```diff
-    if dialog.contents and dialog.scroll_top >= dialog.contents.size
-      dialog.scroll_top = dialog.contents.size - height
-    end
```
The original code unintentionally …
> Fix scrollbar wrongly displayed bug

- lib/reline/line_editor.rb
- test/reline/yamatanooroti/test_rendering.rb
fixed theses indent
```
irb(main):001:1* [
irb(main):002:1*  1, # expect 1 and 2 on the same column
irb(main):003:1*   2,
```
```
irb(main):001:0> {
irb(main):002:1*  x: 1, # expect x: and y: on the same column
irb(main):003:1>   y:
```
```ruby
require 'reline'
Reline.auto_indent_proc = proc { _1.size <= 1 ? 0 : 5 }
Reline.readmultiline('#>') { false }
#>ab
#>   c
#>    d
#>     e
#>     f
#>ab
#>     c
#>     d
#>     e
#>     f
```
new_indent can be larget than previous line. deleted the codition
```ruby
new_indent = @cursor_max if new_indent&.> @cursor_max
```
recalculate `@cursor_max`
```ruby
@cursor_max = calculate_width(line)
@cursor_max = calculate_width(@line)
```
> Fix indent when type "[\n" or "{\n" in irb

- test/reline/helper.rb
- test/reline/test_reline.rb
Fixes the same issue at https://github.com/ruby/ruby/pull/5417
`ruby` is not always available in certain build environments and configure options (e.g. --program-suffix)
This patch tries to choose an appropriate command line for spawning a fresh Ruby process, based on EnvUtil implementation in ruby/ruby's test suite.
Plus when this library is directly mirrored into ruby/ruby, prefer EnvUtil available there over the implementation in this library's test suite.
----
✅ verified the test suite passes when mirrored to ruby/ruby
> test_dumb_terminal: "ruby" command is not always available

- lib/reline/line_editor.rb
- test/reline/yamatanooroti/test_rendering.rb
Fixed #505 
When newline is added at the end of the buffer, reline re-calculates previous line indentation.
Reline needs to render both previous line and added line, but renderes only added line.
I changed `rerender_added_newline` to also render previous line.
> Fix line rendering when newline is added at the end of the buffer

- lib/reline.rb
FILENAME_COMPLETION_PROC and USERNAME_COMPLETION_PROC are not used by Reline.
However, they were added for compatibility with the rb-readline gem.
These constants have been retained and comments added.
```
~/ghq/github.com/ruby/reline remove-unused-constants*
❯ git grep USERNAME_COMPLETION_PROC
~/ghq/github.com/ruby/reline remove-unused-constants*
❯ git grep FILENAME_COMPLETION_PROC
```
> Add comment for unused constants

- lib/reline.rb
- lib/reline/ansi.rb
- lib/reline/general_io.rb
- lib/reline/line_editor.rb
- lib/reline/windows.rb
- test/reline/yamatanooroti/test_rendering.rb
When pressing tab key for a long time, cursor is moving right and left. On the right end, something(`nt` and `----`) is remain displayed.
This behavior is also causing random test failure in `rake test_yamatanooroti`.
These tests failed in my local environment (macOS, Terminal.app, vterm 0.2, looks like fails more frequently compared to ci)
```
test_autocomplete_after_2nd_line
test_autowrap_in_the_middle_of_a_line
test_backspace
test_dynamic_prompt_returns_empty
test_dynamic_prompt_with_newline
test_finish_autowrapped_line_in_the_middle_of_multilines
test_force_enter
test_incremental_search_on_not_last_line
test_insert_line_in_the_middle_of_line
test_insert_newline_in_the_middle_of_buffer_just_after_dialog
test_mode_string_vi
test_mode_string_vi_changing
test_original_mode_string_vi …
```
> Fix the cause of test_yamatanooroti randomly failing

- lib/reline/line_editor.rb
- test/reline/helper.rb
- test/reline/yamatanooroti/multiline_repl
- test/reline/yamatanooroti/test_rendering.rb
Type "(((((\n" in irb
```
irb(main):001:5* (((((
irb(main):002:10*      
```
Then, type "1"
```
irb(main):001:5* (((((
irb(main):002:5*      1
```
The indent number `10` in `irb(main):002:10*` is wrong. It should be `5`.
In this case, `whole_lines` returned `["(((((", "((((("]` and calculated index became 10.
I changed the default argument value of `def whole_lines` to always look at `@previous_line_index`
> Fix wrong indent number in prompt. whole_lines has duplicated line.

- lib/reline/line_editor.rb
- test/reline/yamatanooroti/test_rendering.rb
When you are editing multiline with `irb --noautocomplete` or `IRB_USE_AUTOCOMPLETE=false irb`, TAB completion corrupts the screen.
https://user-images.githubusercontent.com/1780201/221970703-be8f53be-1bc3-4a54-9f4a-08f168ea83a5.mp4
For this example input
```ruby
if 1
Arr█
end
```
preposing is `"if 1\n  "`, target is `"Arr"` and postposing = `"\nend"`
Before this pullrequest, reline was not considering preposing and postposing having `"\n"` in noautocomplete mode.
reference code:
https://github.com/ruby/reline/blob/51b0297e461f6c0e39d5670f8ec4da28694290b6/lib/reline/line_editor.rb#L1420-L1426
> Fix IRB's completion of multiline and noautocomplete

- lib/reline/line_editor.rb
- test/reline/yamatanooroti/test_rendering.rb
This pull request fixes a bug introduced by #507 
When you input long line, longer than the terminal width to irb and type enter, rendering breaks.
```ruby
def aaaaaaaaaa
bbbbbbbbbb
prompt> def aaaaaaaa
prompt> def aaaaaaaa
aa
prompt>   bbbbbbbbbb
prompt>   bbbbbbbbbb
bb
prompt>
prompt> def aaaaaaaa
aa
prompt>   bbbbbbbbbb
bb
prompt>
```
When newline is added to the end of the buffer, reline rerenders last line (because indent might changed) and the added newline.
When the last line is autowrapped (height of last line >= 2), cursor must move up before rerendering the last line, this pull request adds this process.
> Fix: line longer than terminal width breaks rendering

- lib/reline/line_editor.rb
- test/reline/test_key_actor_emacs.rb
Since #434, the <kbd>Del</kbd> key is bound to `:key_delete`, but `:key_delete` doesn't behave like readline does in emacs mode. It moves the cursor left if a character was deleted under the cursor, while in readline, it just deletes the character under the cursor.
line | type | `key_delete` | `em_delete`
-|-|-|-
| `abc\|` | <kbd>DEL</kbd> | `abc\|` | same
| `ab\|c` | <kbd>DEL</kbd> | `a\|b` | `ab\|`
| `ab\|c` | <kbd>DEL</kbd> <kbd>DEL</kbd> | `\|a` | `ab\|`
`:em_delete` is almost <kbd>Del</kbd> like readline, except it also handles the end-of-file situation. Which is annoying because if you type <kbd>Del</kbd> on an empty line, you get EOF instead of no changes.
This fixes it by using `:em_delete` in emacs mode, but also tweaking the behavior of `:em_delete` to only handle EOF when the …
> Use `em_delete` in `key_delete`

- lib/reline/unicode.rb
- test/reline/test_unicode.rb
Fix this uncolored bug
Reline::Unicode.split_by_width did not retain color in previous line.
```ruby
RED="\e[31m"
BLUE="\e[34m"
Reline::Unicode.split_by_width "#{RED}abcde#{BLUE}fg", 4
[["#{RED}abcd", nil, "#{RED}e#{BLUE}fg"], 2]
[["#{RED}abcd", nil, "e#{BLUE}fg"], 2] # e is uncolored
```
> Fix split_by_width to retain color sequences

- lib/reline/line_editor.rb
- test/reline/yamatanooroti/test_rendering.rb
When input lines is larget than screen height, and move cursor up and down, cursor position sometimes overruns
And if you input something, irb will crash. this pull request fixes it.
I think #470 will be fixed.
Left: before, Right: after
https://user-images.githubusercontent.com/1780201/224025150-fd53acd6-7ea1-42fc-8150-76001990518f.mp4
```ruby
calculate_nearest_cursor
...
update_previous_line_index
if @rerender_all
update_line
rerender_all_lines
else
update_line
maybe_prepareing_instance_variables_for_moving_cursor
update_cursor_to_nearest_cursor_position
move_cursor
end
```
↓
```ruby
calculate_nearest_cursor
update_cursor_to_nearest_cursor_position
...
update_line_and_previous_line_index
if @rerender_all
rerender_all_lines
else
maybe_prepareing_instance_variables_for_moving_cursor …
```
> Fix cursor position overrun

- lib/reline/unicode.rb
- test/reline/test_unicode.rb
I also noticed that we don't have good test coverage on `Unicode.take_range` and `Unicode.calculate_width` methods, so the first 2 commits add tests for them.
> Expand the scanned array to later case statement more straightforward

- lib/reline/unicode.rb
- test/reline/test_unicode.rb
Reline::Unicode::OSC_REGEXP `/\e\]\d+(?:;[^;]+)*\a/` has a bug.
```ruby
"text \e]1;OSC\a text \a text \e]1;OSC\a text".scan(Reline::Unicode::OSC_REGEXP)
#=> actual: ["\e]1;OSC\a text \a text \e]1;OSC\a"]
#=> expected: ["\e]1;OSC\a", "\e]1;OSC\a"] 
```
Change
`/\e\]\d+(?:;[^;]+)*\a/`
↓
`/\e\]\d+(?:;[^;\a\e]+)*(?:\a|\e\\)/`
OSC sequence ends with `BEL`(already implemented) or `ST(="\e\\")` (implemented in this pull request).
OSC sequence does not include BEL and ESC inside. (tested in Terminal.app, iTerm2, Alacritty with `printf "text \e]0;WindowTitleInclu\eDingESC\a text"`)
As a side effect, `Reline::Unicode.calculate_width("\e]1;"*10000, true)` gets faster.
I think this pull request does not affect/improve the actual behavior because IRB is not using OSC sequence
> Improve OSC sequence regexp

- lib/reline/unicode.rb
In all usages of `Unicode.take_range`, the last parameter never receives anything:
```
lib/reline/line_editor.rb
751:      str = padding_space_with_escape_sequences(Reline::Unicode.take_range(item, 0, str_width), str_width)
810:          s = Reline::Unicode.take_range(visual_lines[start + i], old_dialog.column, old_dialog.width)
828:          s = Reline::Unicode.take_range(visual_lines[start + i], old_dialog.column, old_dialog.width)
847:          s = Reline::Unicode.take_range(visual_lines[start + i], old_dialog.column, width)
866:          s = Reline::Unicode.take_range(visual_lines[start + i], old_dialog.column + dialog.width, width)
917:        str = Reline::Unicode.take_range(visual_lines_under_dialog[i], dialog.column, dialog.width)
```
So we can drop it to make it easier to …
> Drop Unicode.take_range's optional arg as it's never used

- lib/reline/line_editor.rb
> Drop Dialog#scrollbar_pos as we can store it in a local variable

- .github/workflows/reline.yml
- Gemfile
Reline's test no longer depends on irb.
CI was failing in ruby 2.6 because github:ruby/irb requires ruby >= 2.7
```
Could not find compatible versions
Because every version of irb depends on Ruby >= 2.7
and Gemfile depends on irb >= 0,
Ruby >= 2.7 is required.
So, because current Ruby version is = 2.6.10,
version solving has failed.
```
https://github.com/ruby/reline/actions/runs/4678386950/jobs/8287063665?pr=532
> Remove irb from test dependeicy and from test matrix

- .github/workflows/reline.yml
I reverted the change I made in #533 that removed irb-test from workflow.
I also fixed the bug in irb-test workflow. It was running reline's test instead of irb's test.
`cd irb` is missing and `bundle exec rake test` was running in the wrong directory.
I also add irb's test_yamatanooroti in the workflow
Example of wrong test. 3068 assertions with different encoding is reline's test.
https://github.com/ruby/reline/actions/runs/4678386950/jobs/8287060129?pr=532
> Run IRB test in workflow

- lib/reline.rb
- test/reline/test_reline.rb
If you pass nil to add_dialog_proc, Reline suddenly raise error.
```
% ruby -rreline -e "Reline.add_dialog_proc(:a,nil);Reline.readmultiline('prompt>'){true}"
prompt>/usr/local/lib/ruby/3.3.0+0/reline/line_editor.rb:583:in `instance_exec': no block given (LocalJumpError)
from /usr/local/lib/ruby/3.3.0+0/reline/line_editor.rb:583:in `call'
from /usr/local/lib/ruby/3.3.0+0/reline/line_editor.rb:618:in `call'
...
```
~I chage add_dialog_proc not to accept nil~
I change to remove dialog_proc when nil is passed.
There was no way to remove dialog_proc before this pull request.
> Reline.add_dialog_proc should not accept nil as proc

- lib/reline/line_editor.rb
Fixes https://github.com/ruby/reline/issues/466
#335 was an effort to address #321 (ed_quoted_insert doesn't work properly) but [per the reporter](https://github.com/ruby/reline/issues/321#issuecomment-919170815) the change did not work correctly.
Moreover, it introduced a major regression: Shell job control stopped working in all applications that use reline, notably IRB.
Shells send SIGTSTP [in response to SUSP (C-z)](https://www.gnu.org/software/libc/manual/html_node/Job-Control-Signals.html#index-SIGTSTP) to implement the suspension part of job control. Adding a handler for SIGTSTP opts out of this functionality. For a line oriented terminal program this should be avoided when possible (not to mention, this behavior diverges from readline's)
cc @aycabta
> Revert #335 (Trap TSTP to handle C-z)

- lib/reline/line_editor.rb
- test/reline/test_line_editor.rb
- test/reline/yamatanooroti/test_rendering.rb
Reline can have multiple dialog in random position as an API design, but failed to render it correctly.
This pull-request will enable rendering multiple dialogs correctly.
Left: before, Right: after
https://user-images.githubusercontent.com/1780201/225343025-dbc4b77f-847c-4ff3-b6d4-4db875c74ce0.mp4
Fixes #489
Fixes #458 in another way.
No more remaining whitespaces. Before this pullrequest, white space remained where dialog exist after dialog closes.
Dialog#contents is now used as an offscreen canvas for each dialog.
Dialogs cannot be clear and re-rendered independently in `render_each_dialog`, especially when they are overlapped.
I added `render_dialog_changes`. It can be used in both dialog rendering and dialog clearing.
- Takes all dialog's previous position and next position as …
> Rewrite dialog rendering

- lib/reline/line_editor.rb
- test/reline/yamatanooroti/test_rendering.rb
Fix this redering corrupt bug.
Left: before, Right: after
https://user-images.githubusercontent.com/1780201/227573618-67a2bc4e-4e63-430a-aae7-999560d910c8.mp4
If the terminal height is 5
```
prompt > 1 + 2
=> 3
prompt> if 1
prompt>   2.
```
Reline can only render 3 lines of dialog if the cursor is on line 2.
```
prompt> if 1
prompt>   2.
2.remeinder
2.abs
2.magnitude
```
If reline breaks this rule and render 4 lines
```
prompt>   2.
2.remeinder
2.abs
2.magnitude
2.zero?
```
Reline cannot move cursor to the beginning of line, where `if 1` was displayed.
This is making reline's rendering corrupt.
I changed dialog rendering not to render where it overflows screen.
> Fix dialog corrupts rendering by pushing up input line too much

- download-test_readline.rb
ext/readline is removed from ruby/ruby https://github.com/ruby/ruby/pull/7781
This pull request changes the download source path of ext/readline's test.
(maybe we can have readline test in reline's repository instead of downloading it, or just remove it #539)
> Change readline test download source from ruby/ruby to ruby/readline-ext

- lib/reline.rb
- lib/reline/line_editor.rb
- test/reline/yamatanooroti/test_rendering.rb
Reduce dialog pushing up previous output problem described in #485
Reline should use an appropriate dialog height for completion dialog.
IRB should also use the same dialog height for document dialog, so Reline should provide an API for IRB.
I added `screen_height` (because `screen_width` already exists) and `preferred_dialog_height`
This is the dialog height that does not cause dialog pushup.
If the cursor is on the bottom of the screen and cannot render dialog above cursor, Reline need to push up to render dialog.
I think pushing up about `height / 5` for large screen is acceptable and want to make it like the table below.
| screen height | dialog push up |
| --- | --- |
| 1 | >= 1 (to avoid zero division)|
| 8 | 2 |
| 9 | 3 |
| large | about height / 5 |
`(height + 6) / 5` will meet …
> Use appropriate dialog height and reduce screen pushup problem

- lib/reline/line_editor.rb
- test/reline/yamatanooroti/test_rendering.rb
Fix scrolldown bug.
Left: master branch, Right: this pull request
Scroll down condition was wrong.
In the case below, `@highest_in_all` (total lines, including wordwrap) is 7 and the maximum row index is 6(`@highest_in_all - 1`
```
prompt:0> puts 'Hello World'
Hello World
=> nil
prompt:0> def f
prompt:1>   1
prompt:2>   2; ruby/
prompt:3>   3
prompt:4>   4
prompt:5>   5
prompt:6> end
```
When dialog is going to be rendered in row=3 to row=7 (`ymin == 3` and `ymax == 7` )
```
prompt:0> puts 'Hello World'
Hello World
=> nil
prompt:0> def f
prompt:1>   1
prompt:2>   2; ruby/r
prompt:3>   3       re
prompt:4>   4       rel
prompt:5>  5        reli
prompt:6> end       relin
prompt:7>           reline
```
`ymax` is larger than maximum row index `@highest_in_all - 1` so reline needs to scroll …
> Fix scrolldown condition in dialog rendering

- lib/reline.rb
- lib/reline/line_editor.rb
Fixes: https://github.com/ruby/reline/issues/551
We can create a structure named by its constant. Although writing the name under `Struct` is no problem, it would be better to be omitted it.
Ref: https://docs.ruby-lang.org/en/3.0/Struct.html
Thank you for having me the opportunity. I’m glad to start contributing to open-source projects.
> Omit constant under Struct

- lib/reline/unicode.rb
`get_mbchar_byte_size_by_first_char` isn't used in Reline.
Also, this method implements the same functionality as `String#bytesize` and is unnecessary.
> Remove unused method

- lib/reline.rb
1. Since `Reline::Core` already has `encoding` method, we don't need to get encoding from `IOGate` repeatedly.
2. Because different `IOGate` classes have different input/output setters, we can use that instead of checking the `IOGate`'s class type.
> Refactor Reline::Core

- lib/reline/line_editor.rb
- test/reline/yamatanooroti/test_rendering.rb
Fixes byte_pointer passed to auto_indent_proc when inserting newline.
If there is multiline character, wrong byte_pointer causes invalid byte sequence error.
Fixes #553 and https://github.com/ruby/irb/issues/627
> Fix wrong byte_pointer passed to auto_indent_proc

- lib/reline.rb
- test/reline/test_reline.rb
Workaround for #559
`$stdout.tty?` sometimes change from `false` to `true` in a normal Rails application's `rails console` with combination of `gem spring`.
If it changed to true, Reline should use Reline::ANSI instead of Reline::GeneralIO.
This pull request will make Reline re-initialize `Reline::IOGate` in `readline` and `readmultiline` if needed.
Is there any idea writing test for this?
> Update Reline::IOGate dynamically when it is needed

- lib/reline.rb
- lib/reline/ansi.rb
- lib/reline/line_editor.rb
- test/reline/helper.rb
- test/reline/test_ansi_with_terminfo.rb
- test/reline/test_ansi_without_terminfo.rb
- test/reline/test_config.rb
- test/reline/test_history.rb
- test/reline/test_key_actor_emacs.rb
- test/reline/test_key_actor_vi.rb
- test/reline/test_macro.rb
- test/reline/test_reline.rb
- test/reline/test_string_processing.rb
- test/reline/test_within_pipe.rb
- test/reline/yamatanooroti/test_rendering.rb
Storing the IO gate object in a constant is not ideal given:
- We constantly need to call [`remove_const` and `const_set`](https://github.com/ruby/reline/blob/master/test/reline/helper.rb#L23-L40) in test cases to change its value, which somewhat defeats the purpose of constant.
- But more importantly, with #559 we also need to do it in production code (see #560).
If we combine the above cases, the IO gate object is more suitable to be an attribute of either `Reline::Core` or `Reline::Config`. And this is the direction we'll be working toward to.
To make the above refactor easier, I want to reduce the direct references to `IOGate` in this PR. All existing usages should still refer to `IOGate` as the source of truth, but with either `Core#io_gate` or `LineEditor#io_gate`.
> Reduce direct references to `Reline::IOGate`

- lib/reline/key_stroke.rb
- lib/reline/line_editor.rb
- test/reline/test_key_stroke.rb
- test/reline/yamatanooroti/test_rendering.rb
Fixes #514
When unknown escape sequence is typed, reline prints the escape sequence.
In Mac Terminal.app, the keys are F1~F12 keys, option+A, option+up, etc.
This pull request will change reline to correctly ignore unmatched CSI sequence, SS3 sequence, ESC+char and single ESC input.
> Ignore unhandled escape sequences

- test/reline/yamatanooroti/test_rendering.rb
Without `close`, process `ruby -I#{@pwd}/lib #{@pwd}/test/reline/yamatanooroti/multiline_repl}` will remain until every test ends.
```
% grep -c "close" test/reline/yamatanooroti/test_rendering.rb 
96 → 99
% grep -c "assert_screen" test/reline/yamatanooroti/test_rendering.rb
99
% grep -c "def test_" test/reline/yamatanooroti/test_rendering.rb              
99
```
> Add missing `close` to test_rendering.rb

- lib/reline/ansi.rb
- test/reline/test_ansi_with_terminfo.rb
- test/reline/test_ansi_without_terminfo.rb
Fixes HOME key, END key, Meta + Arrow key problem in some terminal emulator.
Most terminals are vt100 compatible. In vt100 normal mode, ANSI cursor sequence `"\e[A", "\e[B", "\e[C", "\e[D"` will be sent on arrow key press.
("Cursor Control" section of https://vt100.net/docs/vt100-ug/chapter3.html, "Minimum requirements for VT100 emulation" section of https://www.real-world-systems.com/docs/ANSIcode.html)
These arrow key sequence are normally not written in terminfo. This pull request make Reline bind these cursor sequences as default.
HOME `\e[H` and END `\e[F` keys are also categorized as cursor sequence. You can check this by setting [Cursor Key Mode (DECCKM)](https://vt100.net/docs/vt510-rm/DECCKM.html). HOME/END key will change the behavior just like arrow key does.
```ruby
when …
```
> Always set ANSI CSI keybindings for Home, End, and Arrow.

- test/reline/yamatanooroti/multiline_repl
- test/reline/yamatanooroti/test_rendering.rb
Reline was passing `lines=[nil]` to auto_indent_proc when exit with Ctrl-d. This pull request add assertion to auto_indent_proc's parameter in rendering test and add Ctrl-d exit test.
Without #571, test added in this pull request will fail. https://github.com/tompng/reline/actions/runs/5592504740/jobs/10225040010
I think there are several bug that wrong byte_pointer is passed to auto_indent_proc.
Adding a strict assertion for byte_pointer will make many test fail, so I added a loose assertion for now.
> Add assertion to auto_indent_proc's parameter, add Ctrl-d exit test

- lib/reline/version.rb
Diff: https://github.com/ruby/reline/compare/v0.3.6...master
With #569 and #577 both fixed long-standing issues, I think it's worth cutting another release for them.
> Bump version to 0.3.7

- lib/reline/line_editor.rb
Fix it
https://github.com/ruby/reline/issues/558
Do I need to add a test? If so, where?
> Add `kill-word` and `backward-kill-word` keymapping support.

- lib/reline.rb
- lib/reline/ansi.rb
- lib/reline/general_io.rb
- lib/reline/windows.rb
- test/reline/yamatanooroti/test_rendering.rb
Timeout's implementation relies on Thread, which would conflict with `ruby/debug`'s thread-freezing implementation and has casued issues like
- ruby/debug#877
- ruby/debug#934
- ruby/debug#1000
This commit avoids the issue by completely removing the use of Timeout.
> Remove Timeout usage

- bin/generate_east_asian_width
The format of EastAsianWidth.txt seems to change after Unicode 15.1.0 (draft).
15.0.0: https://www.unicode.org/Public/15.0.0/ucd/EastAsianWidth.txt
```
#
#
0000..001F;N     # Cc    [32] <control-0000>..<control-001F>
0020;Na          # Zs         SPACE
0021..0023;Na    # Po     [3] EXCLAMATION MARK..NUMBER SIGN
0024;Na          # Sc         DOLLAR SIGN
```
15.1.0 draft: https://www.unicode.org/Public/draft/UCD/ucd/EastAsianWidth.txt
```
#
#
0000..001F     ; N  # Cc    [32] <control-0000>..<control-001F>
0020           ; Na # Zs         SPACE
0021..0023     ; Na # Po     [3] EXCLAMATION MARK..NUMBER SIGN
0024           ; Na # Sc         DOLLAR SIGN
```
Therefore, `bin/generate_east_asian_width` will fail.
```
% ruby bin/generate_east_asian_width EastAsianWidth-15.1.0-draft.txt …
```
> EastAsianWidth.txt Format Change after Unicode 15.1.0

- bin/generate_east_asian_width
- lib/reline/unicode/east_asian_width.rb
fix #438
The beginning of the comment in `EastAsianWidth.txt` contains the Unicode version.
```
% head -3 EastAsianWidth.txt
% 
```
At least since Unicode 3.2.0, the version seems to be included.
```
% curl --silent https://www.unicode.org/Public/3.2-Update/EastAsianWidth-3.2.0.txt | head -3
#
%
```
So, the version is retrieved from there.
```
% ruby bin/generate_east_asian_width EastAsianWidth.txt | head
class Reline::Unicode::EastAsianWidth
UNICODE_VERSION = '15.0.0'
TYPE_F = /^[#{ %W(
\u{3000}
\u{FF01}-\u{FF60}
\u{FFE0}-\u{FFE6}
%
```
The version is set to `Reline::Unicode::EastAsianWidth::UNICODE_VERSION`.
The variable name `UNICODE_VERSION` is taken from `RbConfig::CONFIG["UNICODE_VERSION"]`.
If the comment format is changed in the future and the Unicode version fails to be …
> Set EastAsianWidth::UNICODE_VERSION

- bin/generate_east_asian_width
- lib/reline/unicode/east_asian_width.rb
`ARGV.first` is the name of the EastAsianWidth file and is not needed for east_asian_width.rb
> Remove `ARGV.first` in east_asian_width.rb

- lib/reline/config.rb
- test/reline/test_config.rb
> Fix config.rb to File.expand_path $include path in inputrc

- lib/reline/general_io.rb
- test/reline/helper.rb
- test/reline/test_reline_key.rb
`make test-all TESTS="reline/test_reline.rb irb/test_cmd.rb"` was failing. Pager is shown and test will stop until you enter `q`.
The reason of the failure is:
- Reline sets IOGate to GeneralIO in teardown
- GeneralIO.get_screen_size returns [1, 1]
- If show-source content exceeds screen height, IRB uses pager
This pull request fixes test teardown to restore IOGate correctly.
show-source's test is also fixed in https://github.com/ruby/irb/pull/720
> Properly restore Reline::IOGate in test teardown

- .github/workflows/ruby-core.yml
- Gemfile
- test/reline/helper.rb
- test/reline/test_face.rb
Because `test-unit-rr` is not a default gem, using it would break CRuby's CI.
I also added a `ruby-core` workflow similar to [IRB's](https://github.com/ruby/irb/blob/master/.github/workflows/ruby-core.yml) that should prevent similar issues in the future.
> Test Reline::Face without mocking

- doc/reline/face.md
- lib/reline/face.rb
- test/reline/test_face.rb
Face supports hex color `'#aabbcc'` but some terminal does not support truecolor. (example: macOS Terminal.app)
This pull request adds fallback to 256color if `ENV['COLORTERM']` is not `'truecolor' | '24bit'`
`0..15` is standard color and high intensity color (this color table is customizable by terminal emulator's config)
`16..231` is 216 color (r,g,b each 6 steps, 6**3 == 216) This pull request uses this part.
`232..255` grayscale 24step. This pull request does not use this part event if the specified color is gray.
Each R,G,B in 216 color are 6 steps, `[0, 95, 135, 175, 215, 255]`
In ruby code, steps are `[0, *95.step(255,40)]`
when value > 95, color index can be calculated by `1 + ((value-95)/40.0).round` or in short, `(value - 35) / 40`
Many tools uses `ENV['COLORTERM'] == …
> Fallback to 256color if COLORTERM != truecolor

- lib/reline/kill_ring.rb
Found this while auditing uses of `object_id` in `ruby/ruby`. Pulled out from ruby/ruby#9276
This PR replaces an `object_id` comparison with an `equal?`, which has the same semantics, but is faster and doesn't trigger allocation of IDs for these objects.
> Replace `object_id` comparison with `equal?`

- lib/reline/line_editor.rb
- test/reline/yamatanooroti/multiline_repl
- test/reline/yamatanooroti/test_rendering.rb
```ruby
2.times do
puts
puts
end
```
It happens when completion candidates of autocomplete at the beginning of the line is empty.
Example: With `irb --type-completor` or with ruby/irb:master that disabled empty target completion.
> Fix pasting tab-indented code crash

- reline.gemspec
This PR adds [metadata](https://guides.rubygems.org/specification-reference/#metadata) for [rubygems.org](https://rubygems.org/gems/reline?locale=ja)
> Add metadata for rubygems.org

- lib/reline/face.rb
I think this has a few benefits:
1. Most terminal themes generally don't change or only pick similar colors for their black and white colors, so it's more likely to be consistent across terminals/themes.
2. They don't have the potential color-blind issues that other color options may have.
3. We won't need additional changes for no color mode.
> Use gray and bright-white as the default dialog theme

- test/reline/yamatanooroti/multiline_repl
This avoids the frozen literal warning in Ruby 3.4.
> Make mutated string in yamatanooroti explicitly mutable

- lib/reline/ansi.rb
- lib/reline/general_io.rb
- lib/reline/line_editor.rb
- lib/reline/windows.rb
- test/reline/test_line_editor.rb
Reline didn't send ansi color sequence before if TERM=dumb, but now it sends color reset sequence `"\e[0m"`.
Fixing this, IRB does not need to remove `"\e[0m" from output in integration test.
> Do not send color reset sequence when GeneralIO is used

- lib/reline/line_editor.rb
- test/reline/yamatanooroti/test_rendering.rb
`show-mode-in-prompt` was broken in v0.5.0.pre.1
Fixes it by adding prompt_mode to prompt list calculation dependencies.
To enable `show-mode-in-prompt`, add this to `.inputrc`
```
set editing-mode vi
set show-mode-in-prompt on
set vi-ins-mode-string (ins)
set vi-cmd-mode-string (cmd)
```
> Add mode_string to prompt calculation dependencies

- lib/reline.rb
When TERM=dumb (test-mode), escape sequence of completion dialog is printed. Reline didn't print it in `ver <= 0.4.2`.
This pull request disables adding dialog when TERM=dumb to make the test-mode difference between Reline versions.
This why TERM=dumb completion dialog was disabled in Reline < 0.4.2
```ruby
class Reline::GeneralIO
def self.get_screen_size
[1, 1] # Rendering dialog is skipped because there is no space to render completion dialog
end
end
```
In master branch, using `screen_size=[1,1]` is not suitable for testing. Using screen_size=[1,1] in master branch will be
```
$ TERM=dumb irb
i
```
Printing only one character to make the output fit in [1,1] is an expected behavior. (I'm not sure printing `i` is correct)
> Disable dialog proc if TERM=dumb

- lib/reline/general_io.rb
- test/reline/helper.rb
- test/reline/test_key_actor_vi.rb
The pasting tests hadn't been working since as early as v0.2.0 (iit passes regardless the pasting state). Since what it tried to cover is already gone for such a long time, I think it's better to write new ones if needed then to keep them around.
And since these tests are gone, the helper methods for just them are also gone.
> Remove useless pasting tests

- lib/reline/version.rb
Diff: https://github.com/ruby/reline/compare/v0.4.3...4928e06
> Bump version to v0.5.0

- lib/reline/line_editor.rb
- test/reline/test_line_editor.rb
Align completion candidates in tab completion(noautocomplete mode) just like Readline.
Uses each_slice and transpose.
Adding `[nil] * n` before `each_slice` to avoid `element size differs` error in `transpose`.
> Align completion menu items like Readline in noautocomplete mode

- lib/reline.rb
- lib/reline/line_editor.rb
- test/reline/yamatanooroti/test_rendering.rb
Fixes #611 and #621
Split logic and state of autocompletion and tab completion
Reline has tab complete and autocomplete.
Tab complete uses
```
@completion_state = NORMAL | COMPLETION | MENU | MENU_WITH_PERFECT_MATCH | PERFECT_MATCH
```
Autocomplete uses
```
@completion_state = NORMAL | JOURNEY
@completion_journey_data
retrieve_completion_block(not stored to ivar, calling every time, causing dialog disappearing bug)
```
It's a separate feature but uses same instance variable `@completion_state` that making hard to fix some bugs.
Tab complete uses
```
@completion_state = NORMAL | COMPLETION | MENU | MENU_WITH_PERFECT_MATCH | PERFECT_MATCH
```
Autocomplete uses
```
@completion_journey_state = CompletionJourneyState.new(line_index, pre, target, post, list, pointer) | nil
```
State is …
> Refactor completion

- lib/reline/line_editor.rb
- test/reline/yamatanooroti/test_rendering.rb
Fixes #625
`line.lstrip` removes `"\v"` `"\t"` `" "` and more spaces. If there are "\v" or "\t", byte_position calculation was wrong.
Change for modify_lines:
Reline::Unicode.calculate_width calculates width of `"\v"` as 2. Default output modifying logic should return two-width character for "\v".
> Fix audoindent including "\v", escape "\v" for rendering

- lib/reline.rb
- lib/reline/ansi.rb
- lib/reline/general_io.rb
- lib/reline/line_editor.rb
- lib/reline/windows.rb
- test/reline/test_key_actor_emacs.rb
Handle SIGINT and SIGWINCH correctly, (just update ivar)
`inner_getc` will periodically check if these signal is fired.
Changed signal check timeout from 0.1 to 0.01. `C-c` is handled here, so 0.1s is too slow. (C-c will delay 0.1s)
Remove handle_cleared because clear(C-l) is not a signal
This will fix #461
This will fix C-c problem when `binding.irb` is executed in non-main thread. `ruby -e "Thread.new{binding.irb}.join"`
Another possible way to correctly handle SIGINT is to use `input.raw{getc == "\C-c"}` instead of using `Signal.trap` and `input.raw(intr:true){}`.
But we have to handle other signals too. (example: `\C-z`). We also have to think for windows.
Note: This pull request DOES NOT fix multiple readline in multithread problem `2.times{Thread.new{Reline.readline'>'}}`
> Handle INT signal correctly

- lib/reline.rb
We should use ensure to ensure `finalize` and `deprep` always called.
If we don't use ensure, these cleanup can be skipped if `->{return}.call` or `throw` is used.
This seems to reduce SystemStackError of #667
But does not solve it. `ruby -Ilib -rreline -e "Thread.new{p Reline.readline'>'};sleep 0.1; p Reline.readline'>'` still raise SystemStackError
> Always call finalize and deprep

- lib/reline.rb
- test/reline/yamatanooroti/test_rendering.rb
Block until other Reline.readline or Reline.readmultiline finish
Diff: [files?w=1](https://github.com/ruby/reline/pull/669/files?w=1)
Combination with #668, I think #667 will be fixed.
> Thread safe readline

- lib/reline/ansi.rb
- lib/reline/terminfo.rb
- test/reline/test_ansi_with_terminfo.rb
- test/reline/test_terminfo.rb
Fix https://github.com/ruby/reline/issues/447 https://github.com/ruby/reline/issues/543
This problem occurs when Fiddle can be loaded, curses can be loaded, and TERM is not registered in Terminfo.
It should also occur at hardcopy terminals and when Terminfo information is low, but no such reports have been received.
Reline should not abort the process because of missing Terminfo.
Reline proceeds with `Reline::Terminfo.enabled? == false` when fiddle or curses cannot be loaded.
And does the same when Terminfo is present but TERM is not.
https://github.com/ruby/reline/blob/ebab2875f1226f877376558d8758bc0e2a1776c7/lib/reline/terminfo.rb#L156-L160
You can check the operation with `TERM=foo bundle exec bin/console`.
ref: `man 3x curs_terminfo`
> Continue processing even if terminfo database couldn't be found

- lib/reline/line_editor.rb
- test/reline/test_key_actor_emacs.rb
- test/reline/test_key_actor_vi.rb
Fixes #675
This commit extracts the upward navigation condition in `LineEditor#input_key` to a new private method, and adds a new alias. This change allows Reline to support upward navigation in when a user has configured `inputrc` to map Shift-Tab to `menu-complete-backward`, a common setting in Bash (>= 4.x).
Instead of special-casing upward navigation in `LineEditor#input_key`, we now allow it to be processed by the branch that calls `process_key`. The extracted method no longer includes the editing mode check since this check is already made by `#wrap_method_call` by the time `#completion_journey_up` (or `#menu_complete_backward`) is called. Since upward navigation is happening in a method other than `#input_key` now, the `completion_occurs` variable that used to be local to …
> Support `menu-complete-backward` command for upward navigation

- lib/reline/line_editor.rb
- test/reline/test_key_actor_emacs.rb
- test/reline/test_key_actor_vi.rb
Test will conflict with #645
Fixes #605 
Most waiting_proc will be cancelled when ARROW keys (and other symbol key) is pressed, but Reline did not implement cancel
```
incremental_search_history
vi_replace_char
vi_next_char
vi_to_next_char
vi_prev_char
vi_to_prev_char
ed_quoted_insert
```
Fixes except ed_quoted_insert.
Vi mode's waiting_operator_proc was complex.
```
c: vi_change_meta
d: vi_delete_meta
y: vi_yank
```
Reline's problem with waiting_operator
- `df_` does not terminate delete_meta
- `dd` should clear line
- `cc` should clear line
- `dc` `dy` `cd` `cy` `yd` `yc` `yy` should cancel waiting_operator
- For `3d5h`, 5 should be used as `@vi_arg` but Reline does not
- ARROW key should cancel waiting_operator
Fixes all of them.
> Refactor waiting_proc and waiting_operator_proc 

- lib/reline/key_actor/emacs.rb
- lib/reline/key_actor/vi_command.rb
- lib/reline/key_actor/vi_insert.rb
- lib/reline/line_editor.rb
I checked [GNU Readline documentation](https://tiswww.case.edu/php/chet/readline/readline.html) and defined key bindings for existing features to match Readline.
Also, I removed key bindings that have key bindings defined but no methods defined.
Removed key bindings:
- em_copy_prev_word
- ed_sequence_lead_in
- em_copy_region
- ed_command
- vi_match
- vi_repeat_prev_char
- vi_redo
- vi_repeat_search_prev
- vi_replace_mode
- vi_substitute_line
- vi_undo_line
- vi_yank_end
- vi_history_word
- vi_repeat_search_next
- vi_substitute_char
- vi_undo
- vi_change_case
> Refactored Default Key Bindings

- lib/reline/line_editor.rb
- test/reline/test_key_actor_vi.rb
```ruby
def current_row
wrapped_lines.flatten[wrapped_cursor_y]
end
```
`wrapped_cursor_y` does not exist, and raises NoMethodError.
Old implementation of `vi_to_column` is counting width. vi does it, Readline's vi-mode does not. It only counts string size.
I Removed the condition `(total.last + mbchar_width) >= current_row_width` because it is not needed in both vi and Readline's behavior.
> Fix vi_to_column which was broken

- lib/reline/line_editor.rb
- test/reline/test_key_actor_emacs.rb
- test/reline/test_key_actor_vi.rb
I implemented Readline’s emacs-editing-mode (C-e) and vi-editing-mode (M-C-j, M-C-m) to switch editing modes. The keymap was aligned with Readline's behavior. But `M-C-m` was used in the yamatanooroti tests, so I decided not to map it.
> Implement changing editing mode

- lib/reline/line_editor.rb
Fixes #596
Using this will prevent inconsistency of `@history_pointer` and `@line_backup_in_history` that caused #596. It also reduce duplicated code.
`generate_searcher` is used in `incremental_search_history`
Both searcher and incremental_search_history was modifying LineEditor's state, making hard to understand the behavior.
Now searcher only searches, does not mutate LineEditor's state.
(Also changed the implementation from Fiber to lambda. )
> Refactor history move and history search

- lib/reline/line_editor.rb
> Remove unused variable

- .github/workflows/reline.yml
Rake install already runs rake build, so there is no need to run rake build before running rake install.
Reference: https://github.com/rubygems/bundler/blob/35be6d9a603084f719fec4f4028c18860def07f6/lib/bundler/gem_helper.rb#L43-L46
Other changes were cosmetic by my editor's linter, which I found beneficial too so I kept them.
> Remove unnecessary rake build before running rake install

- lib/reline/line_editor.rb
- test/reline/yamatanooroti/multiline_repl
- test/reline/yamatanooroti/test_rendering.rb
This feature displays all possible completions with a single tab press if autocomplete is disabled and multiple completions are available. It does not alter behavior when autocomplete is enabled.
> `show-all-if-ambiguous`
> This alters the default behavior of the completion functions. If set to ‘on’, words which have more than one possible completion cause the matches to be listed immediately instead of ringing the bell. The default value is ‘off’.
https://tiswww.case.edu/php/chet/readline/readline.html
To use this feature, add these lines to your `.inputrc` file and start `irb` with `--noautocomplete`:
```.inputrc
set show-all-if-ambiguous on
```
> Implement `show-all-if-ambiguous` feature

- lib/reline/line_editor.rb
- lib/reline/unicode.rb
Split prompt and input_line passed to render_line_differential.
This will improve differential rendering performance in these cases
- prompt changed but input_line is not changed
- input_line changed but prompt is not changed
To separately render prompt and input_line, line items passed to render_line_differential is changed
```ruby
[[0, 12, "prompt> code"], [13, 7, "Dialog1"]]
[[0, 8, "prompt> "], [8, 4, "code"], [13, 7, "Dialog1"]]
```
> Separate prompt and input line in rendering

- lib/reline/line_editor.rb
- lib/reline/unicode.rb
- test/reline/test_unicode.rb
When input line is very long, for example, after pasting `[1,1,1,1,1,1,1,1,...(thousands of items)...,1,1,1]` to IRB, Some cursor move operation and rendering is slow.
Performance of pasting long text will be improved in bracketed-paste #655.
This pull request improves performance of re-rendering long text.
```
$ ruby -e "print ([1]*4000).inspect" | pbcopy
$ irb
irb(main):001> [paste long input here]
...(wait a few seconds)
Press C-l to see rerender time (about 0.25s → about 0.01s)
Press C-a C-e to see ed_move_to_end time (about 10s → about 0.01s)
```
I just forgot to erase the old while loop.
When the input is `1,1,1,1,1,1,1....`, colorized code will be `[BLUE]1[RESET],[BLUE]1[RESET],...`
Reline::Unicode.split_by_width will split into
```ruby
[
"[BLUE]1[RESET],[BLUE]1[RESET],", …
```
> Long line performance

- lib/reline/config.rb
- test/reline/test_config.rb
Reading inputrc had a bug like this
```
$if Ruby
$else
$endif
set editing-mode vi
```
Although the above example is not a nested `$if`, this is caused by nested `$if` bug.
This pull request fixes it, and add nested `$if` tests.
> Fix inputrc nested $if $else $endif bug

- lib/reline/line_editor.rb
- lib/reline/unicode.rb
- test/reline/test_line_editor.rb
- test/reline/test_unicode.rb
When dialog is cleared, we need to restore the text that was hidden behind dialogs.
To implement restoring full width characters hidden behind dialog, `Reline::Unicode.take_range` lacks of feature.
It does not provide where to render the string. column information is missing.
```ruby
Reline::Unicode.take_range('一二三四五a', 2, 5) #=> '二三' # should render at column=2
Reline::Unicode.take_range('a一二三四五', 2, 5) #=> '二三' # should render at column=3
```
Sometimes we need other cut variation depending on adjacent dialog position.
The image below shows a variation of `take_range('一二三四五六七八九', 5, 8, option)`
So I add `Reline::Unicode.take_mbchar_range` that has option `cover_begin, cover_end, padding` and make it return the actual cut position.
```ruby
take_mbchar_range('一二三', 1, 4) #=> ['二', 2, 2] …
```
> Completely support full-width characters in differential rendering

- lib/reline/ansi.rb
- lib/reline/line_editor.rb
- test/reline/yamatanooroti/test_rendering.rb
Fix the bug below
```
$ printf "hello" | ruby -rreadline -e "p Readline.readline('>')"
>hello
"hello"
$ printf "hello" | ruby -Ilib -rreline -e "p Reline.readline('>')"
>
""
```
The string `"hello"` is stored in `@continuous_insertion_buffer`, need to force input before finishing read.
In some environment (in my M2 Mac), `pread` raises IOError, so `rescue Errno::ESPIPE, IOError` change in `ansi.rb` is needed to test it.
> Input with eof and no newline bugfix

- lib/reline.rb
- lib/reline/config.rb
Closes: https://github.com/ruby/reline/issues/693
I added a flag to prevent `.inputrc` from being read repeatedly after loading.
> Avoid reading `.inputrc` repeatedly

- lib/reline/line_editor.rb
- test/reline/yamatanooroti/multiline_repl
Fix this bug (reline-0.5.3). Prompt width calculation was wrong when it contains escape sequence.
> Fix prompt width calculation bug

- lib/reline.rb
- lib/reline/config.rb
- lib/reline/key_actor/base.rb
- test/reline/test_config.rb
- test/reline/test_within_pipe.rb
When inpurc file exists, default key bindings and additional key bindings were cleared after first `Reline.readline`.
```
irb(main):001> 123 (arrow key works)
=> 123
irb(main):002> 123 (arrow key does not work)
```
Changed `config.read` always turns `@loaded` to true. This will make the behavior difference of inputrc file existence small.
Even if inputrc file does not exist, we can still think null file is loaded. This will also avoid attempt loading invalid inputrc file many times.
Config is loaded only once and sets additional_key_bindings. We can't clear additional_key_bindings. We don't need to clear default_key_bindings too.
> Fix default and additional key bindings vanish bug

- lib/reline/key_actor/emacs.rb
- lib/reline/key_actor/vi_insert.rb
- lib/reline/line_editor.rb
- test/reline/test_key_actor_emacs.rb
This pull request moves hardcoded \C-i \C-p \C-n to line_editor's method. Just like we did it to `completion_journey_up`.
vi: \C-n is menu-complete. moves completion even if autocomplete is off.
vi: \C-p is menu-complete-backward. moves completion backward even if autocomplete is off.
\C-i is complete. when autocomplete is enabled, it is menu-complete. unless, it is tab complete
shift-tab is completion-journey-up, a bit different from menu-complete-backward (disabled when autocomplete is off)
Readline can configure `complete`, `menu-complete` and `menu-complete-backward`. Uses the same name to make it configurable in irbrc. The old `complete` method is renamed to `perform_completion`.
> Add name defined in readline to completion key bindings C-i C-p C-n

- lib/reline/config.rb
Perhaps these were described as TODO comments, but it is difficult to see that these functions are not available, so they should be removed.
- bind-tty-special-chars
- blink-matching-paren
- byte-oriented
- enable-keypad
- expand-tilde
- history-preserve-point
- horizontal-scroll-mode
- input-meta
- mark-directories
- mark-modified-lines
- mark-symlinked-directories
- match-hidden-files
- meta-flag
- output-meta
- page-completions
- prefer-visible-bell
- print-completions-horizontally
- show-all-if-unmodified
- visible-stats
I confirmed that grep does not hit with either hyphens or underscores.
```
git grep -e bind-tty-special-chars -e blink-matching-paren -e byte-oriented -e enable-keypad -e expand-tilde -e history-preserve-point -e horizontal-scroll-mode -e input-meta -e …
```
> Remove not implemented variables

- lib/reline.rb
- lib/reline/ansi.rb
- lib/reline/config.rb
- lib/reline/line_editor.rb
- lib/reline/unicode.rb
- test/reline/yamatanooroti/test_rendering.rb
Closes #631
Implemented bracketed paste. Directly inserts pasted text.
This will speedup paste (1100 lines in 8sec → 2600 lines in 8sec)
Stops tab-complete while pasting code that includes tab
Code using tab indentation can be pasted to reline
Reline had a code for bracketed paste but it seems not working.
(Escape sequence for bracketed paste start and end was also wrong)
```
irb(main):001> puts "\e[?2004h";gets
(paste text `text` here and press enter)
^[[200~text^[[201~
=> "\e[200~text\e[201~\n" # this is the correct start and end sequence
```
Readline(>= 8.1) enables bracketed paste by default. `set enable-bracketed-paste off` will disable it.
Readline accepts bracketed paste input `"\e[200~text\e[201~"` even if it's disabled in inputrc.
Changed inputrc read timing. Reline should read …
> Implement bracketed paste insert

- lib/reline/line_editor.rb
- test/reline/test_reline.rb
`require 'reline'` is calling `STDIN.winsize` since reline-0.5.0
This pull request will fixes it.
Fixes the `STDIN.winsize` called in part of #690
> Avoid STDIN.winsize called in `require "reline"`

- lib/reline.rb
- lib/reline/key_actor/emacs.rb
- lib/reline/line_editor.rb
- test/reline/test_key_actor_emacs.rb
- test/reline/yamatanooroti/test_rendering.rb
Implemented the undo method to enable undoing actions on a per-action basis.
Executing undo allows reverting to the previous action. The behavior slightly differs from GNU Readline's undo. While GNU Readline groups character insertions within a certain timeframe, I found this to be unintuitive. Inspired by Zsh Line Editor, I made it so that continuous character inputs can be undone one character at a time.
To decide whether to save an operation history, it was necessary to know whether the action was an insertion or a deletion, as the conditions for saving differ between the two. Hence, I added `DELETE_COMMANDS`. Additionally, I refactored so that keys with any `method_symbol` would pass through `wrap_method_call`.
> Implement the undo command

- README.md
Old linked page cannot be found.
The correct link is https://ruby-doc.org/stdlib/exts/readline/Readline.html.
> Fix broken link that document of readline stdlib

- lib/reline/config.rb
- test/reline/test_config.rb
Fix #657 .
(By the way, please forgive me for using the master branch. I know that is bad practice🙇‍♂️)
> allow space in config value

- lib/reline/key_actor/emacs.rb
- lib/reline/line_editor.rb
- test/reline/test_key_actor_emacs.rb
- test/reline/yamatanooroti/test_rendering.rb
Implemented the redo method to enable reverting undone actions on a per-action basis.
By defining `@position`, I was able to implement the redo command using only `@past_lines`, which was originally defined for the undo command. By saving the current line state in `@past_lines`, the entire mechanism was simplified. Specifically, it works as follows:
* Normal input: Delete all elements after the current position in `@past_lines`, push the input into `@past_lines`, and increase `@position` by 1.
* Cursor movement: Update only the cursor position in `@past_lines`.
* Undo: Decrease `@position` by 1 and return `@past_lines[position]`.
* Redo: Increase `@position` by 1 and return `@past_lines[position]`.
> Implement the redo command

- lib/reline.rb
- lib/reline/config.rb
- lib/reline/key_actor.rb
- lib/reline/key_actor/base.rb
- lib/reline/key_actor/composite.rb
- lib/reline/key_actor/emacs.rb
- lib/reline/key_actor/vi_command.rb
- lib/reline/key_actor/vi_insert.rb
- lib/reline/key_stroke.rb
- lib/reline/line_editor.rb
- test/reline/helper.rb
- test/reline/test_config.rb
- test/reline/test_key_actor_emacs.rb
- test/reline/test_key_actor_vi.rb
- test/reline/test_key_stroke.rb
- test/reline/test_reline.rb
- test/reline/test_reline_key.rb
First step of #708
This will make `:matched` `:matching` check simple and fast, especially after we merge MAPPING(size==256 array) and key_bindings(small hash)
```ruby
key_mapping.keys.select { |lhs|
start_with?(lhs, input)
}
...
:matched if @key_bindings[key]
:matching if @matching_bytes[key]
```
```ruby
@key_bindings = {
[27, 91, 65] => :ed_prev_history,
[27, 91, 50, 48, 48, 126] => :bracketed_paste_start,
}
@matching_bytes = {
[27] => true,
[27, 91] => true,
[27, 91, 50] => true,
[27, 91, 50, 48] => true,
[27, 91, 50, 48, 48] => true,
}
```
```ruby
kb = @key_actors[@editing_mode_label].default_key_bindings.dup
kb.merge!(@additional_key_bindings[@editing_mode_label])
kb.merge!(@oneshot_key_bindings)
Reline::KeyActor::Composite.new([@oneshot_key_bindings, …
```
> Improve key binding match/matching check

- lib/reline.rb
- lib/reline/io.rb
- lib/reline/io/ansi.rb
- test/reline/yamatanooroti/test_rendering.rb
Fixes #537, #616 and #690, the behavior will be more similar to Readline's behavior.
`Reline::ANSI` already partially supports non-tty env, but not fully. This pull request changes `Reline::ANSI` to a general io that supports both tty and non-tty environment.
This pull request will change to always use Reline::ANSI. `Reline::Dumb` is only used for testing when TERM=dumb is set.
> Change Reline::ANSI to a general io

- lib/reline/io/ansi.rb
- test/reline/test_reline.rb
Some test (readline-ext, bundler) expects output of `Readline.readline("prompt>")` to match `/\Aprompt>/`.
Readline prints `"\e[?2004h"` (enable bracketed-paste) before prompt if STDIN and STDOUT is both tty.
```
$ ruby -rreadline -e "Readline.readline 'prompt>'" | ruby -e "p STDIN.read"
"\e[?2004hprompt>a\b\e[Kb\b\e[Kc\n\e[?2004l\r"
```
Readline does not print escape sequence before prompt if STDIN or STDOUT is not a tty. But Reline prints it.
```
$ printf "a\bb\bc\n" | ruby -rreadline -e "Readline.readline 'prompt>'" | ruby -e "p STDIN.read"
"prompt>a\b\e[Kb\b\e[Kc\n"
```
This pull request fixes Reline to align with Readline.
Ruby ci was failing. https://github.com/ruby/ruby/actions/runs/9352049059/job/25739247917
This pull request fixes the problem of Reline side. Unfortunately, test …
> Ensure no escape sequence before printing prompt

- lib/reline.rb
- lib/reline/key_stroke.rb
- lib/reline/line_editor.rb
- test/reline/test_key_stroke.rb
Depends on #709 
Second step of #708
We don't need complex `read_2nd_character_of_key_sequence` and `read_escaped_key`.
This source code commend is partially right (only for ESC keys), but not correct.
```ruby
```
With this inputrc file
```inputrc
"abcd": "[ABCD]"
"ab": "[AB]"
```
Input `ab` is `:matched` and also `:matching` (part of `abcd`). In this case, Readline waits for keyseq-timeout milliseconds.
Input `abc` is `:matching` (part of `abcd`). In this case, Readline waits forever.
It's not ESC specific nor 2nd-char specific.
1. Introduce another state `:matching_matched` for `KeyStroke#match_status`.
2. Refactor key reading. timeout will be `matching_matched ? keyseq_timeout : Infinity`.
> Refactor input key reading

- lib/reline/line_editor.rb
- test/reline/test_reline.rb
When Reline reads EOF, Reline.readline should return nil if and only if input is empty.
Readline
```
$ printf "a\b" | ruby -rreadline -e "p Readline.readline"
nil
$ printf "" | ruby -rreadline -e "p Readline.readline" 
nil
$ printf "a" | ruby -rreadline -e "p Readline.readline" 
a
"a"
```
Reline
```
$ printf "" | ruby -Ilib -rreline -e "p Reline.readline" 
nil
$ printf "a\b" | ruby -Ilib -rreline -e "p Reline.readline"
nil # it was ""
```
We don't need `@first_char`. We just need `current_input.empty?` check.
> Remove instance variable @first_char

- lib/reline/io/ansi.rb
Add xterm key bindings to comprehensive list. Add fallback escape sequence of cursor hide/show.
Reline works perfectly in xterm without fiddle and terminfo.
Add xterm kpp knp kdch1(kdch1 was already added) to comprehensive list because I think it is the most major `ENV['TERM']` value.
Add cursor show/hide escape sequence fallback `"\e[?25h"` and `"\e[?25l"`.
`"\e[?#{number}#{enable ? 'h' : 'l'}"` (Terminal private modes set and rest, DECSET DECRST) is a commonly used escape sequence. Even if terminal emulator does not recognize it, it will be just ignored. Note that GNU Readline always outputs DECSET of bracketed paste `"\e[?2004h"` even if TERM=dumb.
The value is slightly different from `infocmp xterm`. But I think simple one (just reset extension number 25 = cursor visibility) is safer …
> Add more fallbacks when terminfo or fiddle is not available

- lib/reline/line_editor.rb
- test/reline/test_key_actor_vi.rb
In vi command mode, and when cursor is at the beginning of the line, `dhp` or `yhp` will copy a nil to `@vi_clipboard` and tries to paste nil as a text, and raises:
```
lib/reline/line_editor.rb:2348:in `vi_paste_next': undefined method `size' for nil (NoMethodError)
if @vi_clipboard.size > 0
```
> Fix vi_yank or vi_delete_meta copies nil bug

- lib/reline/io/ansi.rb
- test/reline/yamatanooroti/test_rendering.rb
When reline is suspended by Ctrl-z and then resumed by fg command, reline needs to rerender the screen.
STDIN.raw/cooked is reset, so we need to call `raw!`.
Calling winch handler on SIGCONT because window might be resized while suspended. In that case, WINCH handler won't be called.
> Rerender and enter raw mode again by SIGCONT

- lib/reline.rb
- lib/reline/line_editor.rb
- test/reline/yamatanooroti/test_rendering.rb
Fix bug of `print('a'*10); Reline.readline('>')` wrong rendering
Readline prints prompt before any other escape sequence, which is ensured in readline-ext test. Reline follows this in singleline mode.
Just after printing prompt, Reline sets `@rendered_screen.lines = [[[0, prompt_width, prompt]]]` representing that prompt is rendered in column 0.
But in this case
```ruby
Reline.readline 'prompt1>'
print 'foo'
Reline.readline 'bar>'
```
`foobar>` is rendered in terminal screen. `bar>` is not rendered in column 0.
```ruby
print 'foo'
Reline.readline 'bar>'
```
> Fix rendering bug of nomultiline prompt

- test/reline/test_reline.rb
Hash#inspect is proposed to change to `{key: value, non_symbol_key => value}` in https://bugs.ruby-lang.org/issues/20433#note-10
This pull request will make test pass in both current hash inspect style and the proposed hash inspect style.
```diff
- assert_include(actual, "{:key=>value}")
+ assert_include(actual, { key: value }.inspect)
```
Patch that change `Hash#inspect` is here https://github.com/ruby/ruby/pull/10924
`rake test` passes with colon style inspect patch, but `rake test_rendering` fails (2 failure).
This does not affect ruby core ci, so I'd like to fix it after `Hash#inspect` is changed in ruby head.
> Accept colon-style hash in test assertion

- lib/reline/config.rb
- test/reline/test_config.rb
I removed the variables that could be set but had no functionality.
For example, although bell-style could be set, Reline does not have the functionality to sound a bell.
> Remove unused variables

- lib/reline/config.rb
- lib/reline/line_editor.rb
- test/reline/test_config.rb
I implemented re-read-init-file to reload .inputrc.
The default key bindings are not set because they can’t be configured in the current Reline. Given the low usage of inputrc, I believe it’s unnecessary to include them. This was mainly implemented for debugging.
I haven’t written tests for this since I’m unsure how to test inputrc changes. Any suggestions are welcome.
> Implement re-read-init-file

- lib/reline.rb
- lib/reline/line_editor.rb
- test/reline/yamatanooroti/test_rendering.rb
Fix https://bugs.ruby-lang.org/issues/20711
Add test for frequently used pre_input_hook pattern.
> Fix redisplay/insert_text called from pre_input_hook

- lib/reline/config.rb
- test/reline/test_config.rb
This PR adds a test for the reset_variables method in the Reline::Config class. The new test ensures that the method correctly resets internal states. Additionally, the test has been refactored for improved readability.
> Add test for reset_variables in Reline::Config

- lib/reline/line_editor.rb
`def render_differential` contains both LineEditor's rendering logic and Algorithm part of differential rendering.
This pull request splits them into `def render` and `def render_differential`
```ruby
def render
LineEditor specific rendering logic part
construct lines to be rendered to the screen from prompt, input and dialogs
render_differential(new_lines, new_cursor_x, new_cursor_y)
end
def render_differential(lines, cursor_x, cursor_y)
pure alogithm part of differential rendering
independent from promt, input and dialogs
end
```
Now, `render_differential([], 0, 0)` can be reused from other method in LineEditor to clear the screen. `def clear_rendered_lines` is not needed anymore.
> Split render_differential to rendering logic and differential rendering algorithm part

- Gemfile
We need to specify the commit hash to update yamatanooroti because `test_rendering.rb` depends on yamatanooroti's implicit sleep that should be fixed in the future.
> Specify commit hash of yamatanooroti

- lib/reline/history.rb
- lib/reline/line_editor.rb
- lib/reline/unicode.rb
- test/reline/test_history.rb
- test/reline/test_unicode.rb
Fixes #615 and https://github.com/ruby/irb/issues/86
Points:
- Reline::LineEditor only supports utf8 convertible valid byte sequences.
- Not all characters are convertible to utf8.
- Some sjis to utf8 conversion are not reversible.
> Fix Reline crash with invalid encoding history

- lib/reline.rb
- lib/reline/io/ansi.rb
- lib/reline/io/dumb.rb
- test/reline/test_reline.rb
- test/reline/test_unicode.rb
Add timeout to cursor_pos. Some terminal emulator or test code using pty does not respond to cursor position query `\e[6n`. Delay caused by timeout is better than unresponsive.
Fixes #674 and https://github.com/ruby/irb/issues/296
Remove `Reline::IO::ANSI#cursor_pos` fallback to `STDOUT.pread`. Not available in some environment. We don't need inaccurate value.
Change fallback value of cursor_pos to `[0, 0]`. We don't need to return `[dummy_row=1, default_ambiguous_width=1]`
Always fallback east asian ambiguous width to 1.
Note that GNU Readline and zsh also uses ambiguous_width=1. The fallback value was inconsistent, some times 1 and sometimes 2.
> Add a timeout to cursor_pos

- lib/reline/line_editor.rb
- test/reline/test_key_actor_emacs.rb
Readline restores line, cursor position and history index with `"\C-g"`(cancel incremental search). Reline should also restore them.
Moving history is difficult. We should use utility method `move_history`.
Input
```
123\n
456\n
UP
LFET
\C-r
12
\C-g
```
Expected (Readline, this branch)
```
irb(main):001> 123
=> 123
irb(main):002> 456
=> 456
irb(main):003> 45|6
```
Actual
```
irb(main):001> 123
=> 123
irb(main):002> 456
=> 456
irb(main):003> |123
```
input
```
1\n
\C-r
1
TAB
\C-r
1
TAB
```
bug
```
reline/line_editor.rb:1712:in 'block in Reline::LineEditor#incremental_search_history': undefined method 'split' for nil (NoMethodError)
@buffer_of_lines = line.split("\n")
```
> Fix incremental search cancel bug

- test/reline/test_reline.rb
`PTY.spawn` with a block detaches the spawned process and leaves it running in background even after exiting the given block.  It is the responsibility of the caller to clean up the yielded IOs and PID.
https://github.com/ruby/ruby/actions/runs/11148759246/job/30986064044#step:13:950
```
Leaked file descriptor: Reline::Test#test_tty_amibuous_width: 9 : #<File:/dev/pts/0>
Leaked file descriptor: Reline::Test#test_tty_amibuous_width: 10 : #<File:/dev/pts/0>
Leaked file descriptor: Reline::Test#test_tty_amibuous_width: 11 : #<File:/dev/pts/1>
Leaked file descriptor: Reline::Test#test_tty_amibuous_width: 12 : #<File:/dev/pts/1>
Leaked file descriptor: Reline::Test#test_tty_amibuous_width: 13 : #<File:/dev/pts/2>
Leaked file descriptor: Reline::Test#test_tty_amibuous_width: 14 : …
```
> Fix FD leaks

- Gemfile
- test/reline/yamatanooroti/test_rendering.rb
Makes test_rendering faster. Yamatanooroti's wait time is reduced from 0.1 sec to 0.01 sec
rake test_yamatanooroti(vterm-yamatanooroti ubuntu-latest head) 209 seconds → 57 seconds
> Make rendering test faster using updated yamatanooroti

- test/reline/yamatanooroti/test_rendering.rb
Some test can be concatenated. It will improve readability and also makes test a bit fast.
```ruby
def test_foo1
long_setup
write foo1
assert_screen(foo1)
close
end
def test_foo1_and_foo2
long_setup
write foo1
write foo2
assert_screen(foo2)
close
end
def test_foo1_and_foo2_and_foo3
long_setup
write foo1
write foo2
write foo3
assert_screen(foo3)
close
end
def test_foo
long_setup
write foo1
assert_screen(foo1)
write foo2
assert_screen(foo2)
write foo3
assert_screen(foo3)
close
end
```
Concatenated tests
```
test_bracketed_paste_with_undo
test_bracketed_paste_with_undo_redo
test_longer_than_screen_height
test_longer_than_screen_height_with_scroll_back
test_longer_than_screen_height_with_complex_scroll_back
test_autocomplete_long_with_scrollbar
test_autocomplete_long_with_scrollbar_scroll
```
> Concatenate some rendeing test

- test/reline/test_reline.rb
- test/reline/yamatanooroti/test_rendering.rb
https://github.com/ruby/reline/actions/runs/11187507536/job/31104699331#step:13:1064
```
Children under /tmp/rubytest.m48l5o:
* -rw------- 1 101 2024-10-02 17:43:51 +0000 rubyfile20241002-60503-bhbfgq
```
> Fix tempfile leaks

- lib/reline/config.rb
- test/reline/test_config.rb
Fixes #603
The inputrc file below will add `"\ec"` to additional key binding but does not add `"\xE3"`. This behavior is different from Readline but I believe this is better.
```Readline
"\M-c": "[You input M-c]"
```
Also supports these formats
```
"\M-\C-x": key
"\Meta-\C-x": key
"\Control-\Meta-x": key
Meta-c: key
Control-c: key
Meta-Control-c: key
C-M-c: key
```
Using this inputrc file,
```Readline
"\M-c": "[You input M-c]"
```
`"\M-c"` is `"\xE3"`. Readline only assign `"\xE3"` to the right hand side key. Terminal emulator that supports utf-8 does not send `"\xE3"` by alt+c because `"\xE3"` is part of a valid utf-8 string.
When you enter `"あ" == "\xE3\x81\x82"`, Readline thinks the input is `"\M-c" + [invalid two bytes]`.
```
ruby -rreadline -e "Readline.readline '>'"
>[You input …
```
> Allow utf-8 safe meta key mapping in inputrc

- lib/reline/io/ansi.rb
- test/reline/test_ansi_without_terminfo.rb
Added `\eOA \eOB \eOC \eOD \eOF \eOH` (arrow keys, home key, end key for application mode) to default key bindings.
Adding this, we can reduce `set_default_key_bindings_comprehensive_list`.
We added ANSI CSI cursor keys in https://github.com/ruby/reline/pull/569.
This pull request adds SS3 keys that we forgot to add. https://vt100.net/docs/vt100-ug/chapter3.html#T3-6
Removed them because these are not specified in terminfo for any terminal emulator.
I think the bytes `[27, 71, 65..68]` is a mistake of `[27, 79, 65..68]`
In KDE source code, arrow keys are `CSI + (A|B|C|D)` or `SS3 + (A|B|C|D)`
https://invent.kde.org/utilities/konsole/-/blob/master/data/keyboard-layouts/default.keytab?ref_type=heads#L62-72
> Add cursor keys for application keypad mode to default key bindings

- lib/reline/line_editor.rb
- test/reline/test_key_actor_emacs.rb
Fixes #760
Continuous tab completion is possible in GNU Readline.
If dig_perfect_match_proc is set, continuous tab completion will be disabled.
`dig_perfect_match_proc` is used in IRB to show document when pressing TAB after perfect match completion.
In such case, setting dig_perfect_match_proc is a hook intended to disable continuous completion and do something else.
> Support continuous tab completion

- lib/reline.rb
- lib/reline/io/ansi.rb
- lib/reline/io/dumb.rb
- lib/reline/line_editor.rb
- test/reline/helper.rb
- test/reline/test_key_actor_emacs.rb
- test/reline/test_key_actor_vi.rb
- test/reline/test_line_editor.rb
- test/reline/test_macro.rb
- test/reline/test_string_processing.rb
Fix #755. Use IO object's encoding to separate  from global `Encoding.default_external`.
For example:
```ruby
require 'reline'
::Encoding.default_external = ::Encoding::ASCII_8BIT
::Encoding.default_internal = ::Encoding::ASCII_8BIT
input = STDIN.dup
input.set_encoding(Encoding::UTF_8)
Reline.input = input
ascii_text = Reline.readline('prompt > ', false)
$stderr.puts ascii_text.encoding.to_s
```
and get `UTF-8`:
```
prompt > こんにちは
UTF-8
```
> Use IO's encoding instead of Encoding.default_external

- lib/reline/io/windows.rb
- lib/reline/line_editor.rb
- test/reline/yamatanooroti/test_rendering.rb
This is part of supporting windows for reline CI using yamatanooroti.
This PR contains the following changes. There are independent to windows specific yamatanooroti changes.
- Windows specific test fix, not related yamatanooroti.
- Changes for conhostV1 (Command Prompt Window, legacy mode ON), includes bug fix.
- Follows reline changes.
- Supporting frozen string literal.
> Windows fix

- lib/reline/line_editor.rb
- lib/reline/unicode.rb
- test/reline/test_unicode.rb
Remove unused value from Reline::Unicode method's return value
```ruby
Reline::Unicode.split_by_width('0123456789', 3)
#=> [["012", nil, "345", nil, "678", nil, "9"], 4]
Reline::Unicode.split_line_by_width('0123456789', 3)
#=> ["012", "345", "678", "9"]
```
IRB uses legacy split_by_width. We need to rename it for refactored implementation and add a legacy split_by_width back.
```ruby
lines, _ = Reline::Unicode.split_by_width
str = "%s..." % lines.first
```
```ruby
Reline::Unicode.split_by_width('0123456789', 3)
#=> [["012", "345", "678", "9"], 4]
```
`Reline::Unicode.em_forward_word` `Reline::Unicode.vi_big_forward_word` and more methods returned `[byte_size, visible_width]` but `visible_width` part is unused.
These method didn't had tests. Tests are added to ensure this change didn't …
> Remove unused things from reline/unicode.rb

- lib/reline/line_editor.rb
- lib/reline/unicode.rb
- test/reline/test_key_actor_emacs.rb
- test/reline/test_unicode.rb
`LineEditor#perform_completion` was complicated.
When autocomplete is off, state is NORMAL, show_all_if_ambiguous is set, input is `1.ab[TAB]`
```
L857: state change to COMPLETION
L874: calls complete_internal_proc to retrieve completion
L888: state change to MENU_WITH_PERFECT_MATCH
L889: calls perform_completion itself recursively
L874: calls complete_internal_proc just to set menu
L876: state change to PERFECT_MATCH
```
It turned out that CompletionState::COMPLETION was not needed at all.
This pull request simplifies the flow.
Fixes tab completion with completion-ignore-case.
Unintentionally fixes bug related to the complex flow. Typing `1.ab[TAB][DELETE_CHAR_OR_LIST]` wrongly triggered show_document.
> Refactor perform_completon

- lib/reline/line_editor.rb
- test/reline/test_key_actor_emacs.rb
- test/reline/test_line_editor.rb
Reline's completion target calculation has a bug
```ruby
require 'reline'
Reline.completion_proc = proc { |target, preposing, postposing|
puts; p(preposing:, target:, postposing:); exit
}
Reline.readline 'prompt> '
```
```
prompt> foo"bar[TAB]
{:preposing=>"foo", :target=>"bar", :postposing=>""}
```
Preposing is `foo`, target is `bar`, and `"` disappears. This bug is a blocker of fixing #444
This pull request:
```
prompt> foo"bar[TAB]
{:preposing=>"foo\"", :target=>"bar\"", :postposing=>""}
```
Preposing is `foo"`.  Target is `bar"`. Quote that is appended to target is the root cause of #444.
One test that began failing is deleted because readline-ext does not act like the behavior expected in that test.
> Fix completion quote, preposing and target calculation bug

- test/reline/test_line_editor.rb
* http://rubyci.s3.amazonaws.com/ubuntu/ruby-master/log/20241124T211003Z.fail.html.gz
* https://github.com/ruby/ruby/actions/runs/11997494018/job/33443159770
> Removed redundant argument at Reline::LineEditor::CompletionBlockTest

- lib/reline.rb
- lib/reline/key_stroke.rb
- lib/reline/line_editor.rb
- test/reline/helper.rb
- test/reline/test_key_stroke.rb
- test/reline/test_line_editor.rb
Depends on #712
Third step of #708
LineEditor was handling multibyte input with `@multibyte_buffer`. I think it should be done in keystroke recognizing layer.
We can handle multibyte character by `:matching | :matched | :matching_matched` mechanism just like other keystroke inputs.
When invalid byte is input to Reline, Reline does not respond to any key except arrow keys.
```
$ irb -Eus-ascii
irb(main):001> type something and then input multibyte character without using paste
```
You can not input anything because `@multibyte_buffer` never become a valid string.
This pull request considers invalid string as `:matching_matched`. It can be a broken string (:matched) and it can also be part of a valid multibyte character (:matching).
This way, if Reline doesn't receive next bytes within …
> Handle multibyte character input by KeyStroke

- .github/workflows/truffle-ruby-test.yml
Background: https://github.com/ruby/irb/issues/1032
Ref: https://github.com/ruby/irb/pull/1035
Similar to IRB, I have separated the TruffleRuby workflow from reline.yml.
> Extract TruffleRuby workflow from reline.yml

- lib/reline/line_editor.rb
- test/reline/helper.rb
- test/reline/test_key_actor_emacs.rb
It was not working because `RELINE_TEST_ENCODING` was not environment variable.
> Fix RELINE_TEST_ENCODING

- lib/reline/line_editor.rb
When target and candidate encoding is incompatible, `item.start_with?(target)` check was skipped.
> Don't skip start_with check on encoding-incompatible candidates

- test/reline/test_config.rb
Failure: test_empty_xdg_config_home(Reline::Config::Test) /home/pterjan/reline/test/reline/test_config.rb:563:in `test_empty_xdg_config_home'
560:     expected = File.expand_path('~/.config/readline/inputrc')
561:     FileUtils.mkdir_p(File.dirname(expected))
562:     FileUtils.touch(expected)
=> 563:     assert_equal expected, @config.inputrc_path
564:   ensure
565:     FileUtils.rm(expected)
566:     ENV['XDG_CONFIG_HOME'] = xdg_config_home_backup
<"/tmp/test_reline_config_4131165/.config/readline/inputrc"> expected but was
<"/etc/inputrc">
> Fix tests failing when INPUTRC is defined

- lib/reline/io/ansi.rb
- test/reline/yamatanooroti/test_rendering.rb
Fixes #735
Considering this kind of code. This code doesn't work well.
```ruby
height, width = STDIN.winsize
Signal.trap(:WINCH){ height, width = STDIN.winsize }
loop do
cui_game_render(width, height)
if game_requires_user_text_input
user_input = Reline.readline('>')
end
end
```
User defined WINCH handler won't be called when window size is changed while reading input in `Reline.readline`. Same for SIGCONT.
This pull request fixes it.
We don't need to consider about user-defined WINCH handler prints something and corrupt Reline's screen. User-defined handler is expected to never print to STDOUT.
```ruby
Signal.trap(:WINCH) do
puts "winsize changed"
clear_screen
rerender_game_screen
end
loop{print "\e[H";sleep 0.0001}
```
> Call user defined sigwinch and sigcont handler

- lib/reline.rb
- lib/reline/io/ansi.rb
- lib/reline/io/dumb.rb
- lib/reline/io/windows.rb
- lib/reline/line_editor.rb
- test/reline/test_line_editor.rb
- test/reline/test_macro.rb
Rendering gets slow after you enter `Thread.new{loop{}}` to IRB.
Every `STDOUT.write` call seems to pass execution to the cpu bound thread, making rendering slow.
Minimizing the number of STDOUT.write call will improve it.
Before
https://github.com/user-attachments/assets/b34dd1f2-bb79-4373-88d5-353fda2fe3bf
After
https://github.com/user-attachments/assets/a33f2e01-2591-4d45-84f5-6f43d1a067da
While trying `Thread.new{loop{}}`, be careful not to press TAB key. Loading RDoc document will hang up.
> Implement buffered output to Reline::ANSI

- lib/reline.rb
- lib/reline/io/windows.rb
- lib/reline/key_actor/base.rb
- lib/reline/key_actor/emacs.rb
- lib/reline/key_actor/vi_command.rb
- lib/reline/key_actor/vi_insert.rb
- lib/reline/key_stroke.rb
- lib/reline/line_editor.rb
- test/reline/helper.rb
- test/reline/test_key_actor_emacs.rb
- test/reline/test_key_actor_vi.rb
- test/reline/test_key_stroke.rb
- test/reline/test_macro.rb
- test/reline/test_reline_key.rb
- test/reline/yamatanooroti/test_rendering.rb
Depends on #713
Fourth step of #708
Combines KeyActor::XXX_MAPPING(single byte to method symbol) with key_bindings(escape sequence to method symbol)
This will simplify the implementation of keys in LineEditor.
We can remove `key.instance_of?(String)` `key.is_a?(Symbol)` check.
Reline::Key structure will be simple.
```ruby
EOF:          Key{ char: nil, combined_char: nil, with_meta: false}
Normal key:   Key{ char: number, combined_char: number, with_meta: false}
ESC+key:      Key{ char: number, combined_char: number|0x80, with_meta: true}
Binding key:  Key{ char: symbol, combined_char: symbol, with_meta: false}
EOF:   Key{ char: nil, combined_char: nil}
Other: Key{ char: string, method_symbol: symbol}
```
Key can contain string.
This means we can assign bracketed-pasted string to a key. …
> Merge key mapping with key bindings

- lib/reline/line_editor.rb
- test/reline/test_key_actor_emacs.rb
Undo and redo should not perform auto indentation. It should not change the indentation. Instead, it should restore previous indentation and revert to the previous state.
```
irb(main):001>
```
Paste `"  1\n  2"`
```
irb(main):001>   1
irb(main):002>   2
```
Paste `"  1\n  2"`
```
irb(main):001>   1
irb(main):002>   2  1
irb(main):003>   2
```
Undo
```
before
irb(main):001>   1
irb(main):002> 2
after
irb(main):001>   1
irb(main):002>   2
```
Redo
```
before
irb(main):001>   1
irb(main):002>   2  1
irb(main):003> 2
after
irb(main):001>   1
irb(main):002>   2  1
irb(main):003>   2
```
> Undo and redo should restore indentation

- lib/reline/unicode.rb
- test/reline/test_unicode.rb
Depend on #759 (split some commits to it)
Rewrite them with about -250 lines.
Update questionable test case.
Using get_prev_mbchar_size and get_next_mbchar_size in a `while` loop is extreamly inefficient.
Using `take_while` to an array of grapheme_cluster is simple and fast enough.
Scenario: paste 2KB text `aaaaa...aaaaa` to IRB and press OPTION+LEFT.
```
irb(main):002> Reline::Unicode.em_backward_word('a'*2000,2000)
processing time: 0.265469s
=> [2000, 2000]
irb(main):002> Reline::Unicode.em_backward_word('a'*2000,2000) 
processing time: 0.001357s
=> 2000
```
> Refactor Reline::Unicode ed_ vi_ em_ methods

- lib/reline.rb
- lib/reline/io.rb
- lib/reline/key_actor/vi_insert.rb
- lib/reline/line_editor.rb
- test/reline/helper.rb
- test/reline/test_key_actor_emacs.rb
- test/reline/test_key_actor_vi.rb
Bracketed paste will be changed to `Reline::Key.new(pasted_content, :insert_multiline_text)`.
This will simplify handling undo/redo of bracketed paste.
Quoted insert will be changed to `Reline::Key.new(char_to_be_inserted, :insert_raw_char)`.
`def ed_quoted_insert`(renamed to `insert_raw_char`) does not need to use `waiting_proc` anymore.
> Change quoted_insert and bracketed_paste to a single key input

- test/reline/test_reline.rb
Same as https://github.com/ruby/reline/pull/510, 'ruby' command is not always available so don't rely on that specific name.
> test_tty_ambiguous_width: Use Reline.test_rubybin

- lib/reline/line_editor.rb
- test/reline/test_key_actor_emacs.rb
Simplify the complicated flow of waiting_proc, wrap_method_call and run_for_operation.
1. Block passed to run_for_operators was always the same. Change to just simply call `wrap_method_call`.
2. Stop passing `method_obj` to another method.
3. wrap_method_call now handles waiting_proc (to reduce duplicated code)
4. Reduce duplicated code in `process_key`
5. Reduce duplicated code that handles `@vi_waiting_operator` in `process_key` and in `run_for_operators`
6. Use `__send__` instead of `wrap_method_call(@vi_waiting_operator, ...)`  because `@vi_waiting_operator` is not a key-bounded method.
7. Stop calling `ed_argument_digit` in specific condition. Instead, implement vi_zero and ed_digit correctly.
> Refactor handling key in LineEditor

- lib/reline.rb
- lib/reline/line_editor.rb
- test/reline/yamatanooroti/test_rendering.rb
Pasting 10 lines of code into terminal with screen height = 5
```
Actual screen (Reline 0.6.0)
irb(main):001> 1.tap do
irb(main):002>   2
irb(main):003>   3 
irb(main):004>   4
irb(main):005>   5█
Expected screen (Reline <= 0.5.12)
irb(main):006>   6
irb(main):007>   7
irb(main):008>   8 
irb(main):009>   9
irb(main):010> end█
```
2. If you press Ctrl+C, irb crashes with the error below. Pressing other key will update the screen to the expected result.
```
/Users/tomoya.ishida/.rbenv/versions/3.4.1/lib/ruby/3.4.0/reline/io/ansi.rb:289:in 'String#*': negative argument (ArgumentError)
write "\n" * x
^
from /Users/tomoya.ishida/.rbenv/versions/3.4.1/lib/ruby/3.4.0/reline/io/ansi.rb:289:in 'Reline::ANSI#scroll_down'
from /Users/tomoya.ishida/.rbenv/versions/3.4.1/lib/ruby/3.4.0/reline/line_edi …
```
> Fix bracketed paste and scrolling bug

- lib/reline/line_editor.rb
- test/reline/yamatanooroti/test_rendering.rb
I have changed the Enter key behavior so that pressing Enter in the middle of a line adds a new line even if the input can be confirmed. Pressing Enter at the end of a line will confirm the input as before.
If you prefer the previous behavior, you can set `ed_force_newline` in inputrc to allow confirmation when pressing Enter in the middle of a line. The existing Alt+Enter functionality remains unchanged.
https://github.com/user-attachments/assets/f326345b-540b-45e8-ba1f-705f61177bd6
> Enter newline if cursor position is middle of input

- lib/reline/key_stroke.rb
Fix typo: marco -> macro.
We found it at [reline code reading](https://rubygems-code-reading.connpass.com/event/338722/).
> Fix typo: marco -> macro

- reline.gemspec
The installer of `ruby/ruby` don't support `Dir.glob` style gemspec. We need to specify all of file list explicitly.
> Migration for bundled gems

- Gemfile
Need for running readline-ext test using Reline as Readline. readline is changed from default gem to bundled gem in Ruby 3.5.0.dev
> Add gem readline to Gemfile to fix failing ci jobs: readline 

- lib/reline/io/ansi.rb
This constant is unused since #769
> Remove unused constant CAPNAME_KEY_BINDINGS

- lib/reline/line_editor.rb
Change `@old_input_lines` to a local variable
Rename `@input_lines` `@input_lines_position` to `@undo_redo_history` `@undo_redo_index`
Rename `def push_input_lines` to `def push_undo_redo`. (we have `def move_undo_redo`)
The meaning of `input_lines` is similar to buffer_of_lines and confusing.
> Refactor undo redo

- lib/reline/io/ansi.rb
- test/reline/test_reline.rb
Reline::ANSI have a read buffer. We don't need to write read bytes back to STDIN only in a few case.
```ruby
@buf #=> [A, B, C]
@output << "\e[6n"
stdin.read_partial #=> "DE" + "\e[ROW;COLUMNR" + "FG"
@buf.concat ("DE" + "FG").bytes
@buf #=> [A, B, C, D, E, F, G]
```
This will reduce the effort (example: https://github.com/kateinoigakukun/irb.wasm/pull/24) of making Reline work with wasm
> Use Relin::ANSI's buffer instead of calling STDIN.ungetc

- Gemfile
Fix ci failure.
Fiddle is only used in windows. I think we need to do these later
- Show a warning message when `require 'fiddle` fails
- Determine which to use: Reline::Windows(fiddle) or Reline::ANSI(no fiddle) without using fiddle in windows.
> Add gem fiddle to Gemfile (Only used in windows)

- .github/workflows/gh-pages.yml
- .gitignore
- .rdoc_options
- Gemfile
- Rakefile
- doc/Index.md
- lib/reline.rb
Similar to `ruby/irb`'s setup:
> Basic setup for Reline's official documentation website

- lib/reline/io/ansi.rb
There are some environment that IO#winsize raises Errno::EINVAL and Errno::EOPNOTSUPP
Errno::EOPNOTSUPP reported in https://github.com/ruby/irb/issues/1090
Errno::EINVAL is rescued in irb(https://github.com/ruby/irb/pull/657#discussion_r1274546479)
Instead of rescuing ENOTTY, ENODEV, EINVAL, EOPNOTSUPP (and maybe more errnos), this pull request changes to rescue SystemCallError.
> Rescue more errors in get/set_screen_size

- lib/reline/key_actor/emacs.rb
- lib/reline/line_editor.rb
- test/reline/test_key_actor_emacs.rb
After using incremental search, I sometime want to go back to the end of history.
Reline is missing an implementation for [`end-of-history` from Readline](https://tiswww.case.edu/php/chet/readline/rluserman.html#index-end_002dof_002dhistory-_0028M_002d_003e_0029).
This adds it.
> Implement end-of-history

- lib/reline/config.rb
- test/reline/test_config.rb
This PR introduces a check to detect and warn about encoding inconsistencies between the `inputrc` file (specified via the `INPUTRC` environment variable) and `Encoding::default_external`. The goal is to prevent or help diagnose `ArgumentError: invalid byte sequence` errors that can occur, for example, during regular expression processing, if the `inputrc` file contains byte sequences incompatible with `Encoding::default_external`.
Currently, when an `inputrc` file specified by the `INPUTRC` environment variable is loaded, its content is processed. An attempt is made to handle encoding, for instance, using `x.encode(Reline.encoding_system_needs)`.
However, this encoding step does not always guarantee that all byte sequences become valid for `Encoding::default_external`. If the source …
> Add validation for Encoding.default_external

- lib/reline/io/ansi.rb
- test/reline/yamatanooroti/test_rendering.rb
There was a mystery of `0x16` in Reline. There is no test and no source code comment.
`0x16` seems to be inserted in some case (what case?) in some way (how?) but nobody knows how and why.
```ruby
(c == 0x16 && @input.tty? && @input.raw(min: 0, time: 0, &:getbyte)) || c
```
It turned out that this is 0x16 came from a configuration of terminal emulator `Escape non-ASCII input with Control-V`
(https://github.com/ohmyzsh/ohmyzsh/issues/7412)
With this configuration, every non-ascii byte will be escaped with `\C-v`
```ruby
irb> STDIN.raw{STDIN.readpartial(100)} # input あ = "\xE3\x81\x82"
=> "\x16\xE3\x16\x81\x16\x82"
irb> print "\e[?2004h"; STDIN.raw{STDIN.readpartial(100)+STDIN.readpartial(100)} # paste あ
=> "\e[200~\x16\xE3\x16\x81\x16\x82\e[201~"
```
Now we can add a test and a comment
> Add a test for non-ascii char input escaped with C-v

- lib/reline.rb
- lib/reline/io.rb
- lib/reline/io/ansi.rb
- test/reline/yamatanooroti/test_rendering.rb
quoted_insert timeout was 1000 times larger. (forgot to do `.fdiv(1000)`)
Fix a bug that readline unexpedly end when quoted_insert timed out. (Avoid insert_raw_char char=nil and use `''` instead when timed out)
Fix this bug:
```
$ LANG=C irb
irb(main):001> (input \C-v あ)
(irb hangs and exits after 500 second)
```
> Fix quoted insert with invalid byte input

- lib/reline/unicode.rb
- test/reline/test_unicode.rb
Currently, Reline assumes that a grapheme cluster has 0, 1 or 2 width.
This assumption is not correct. A single grapheme cluster `はﾟ` will be rendered in three column width. (#832)
> Support grapheme cluster that has width >= 3
