reline.gemspec

Update homepage url in gemspec

---

lib/reline.rb
lib/reline/history.rb
test/test_history.rb

Classify `Reline::HISTORY`.
And added [`test/readline`](https://github.com/ruby/ruby/tree/trunk/test/readline) based test.

Add to `class Reline::History` and test.

---

lib/reline/history.rb
test/test_key_actor_emacs.rb

Removed unused methods in application code.

Remove unused method

---

download-test_readline.sh

Failed CI.
see: https://travis-ci.org/ruby/reline/builds/559412759
Add test file.

Fix failed CI

---

Rakefile

Fix encoding list

---

README.md

Added TravisCI status in README.

Add TravisCI status in README

---

.github/workflows/macos.yml
.github/workflows/windows.yml

Add GitHub Actions for Windows and MacOS.

Add GitHub Actions for Windows and MacOS

---

.github/workflows/macos.yml
.github/workflows/ubuntu-rvm.yml

Added download test readline files in GitHub Actions.
NOTE: Ubuntu and Mac only.

Add download test readline in GitHub Actions

---

.github/workflows/ubuntu.yml

Added CI in Ruby 2.5 and 2.6 with Ubuntu.

Add CI in Ruby 2.5 and 2.6 with Ubuntu.

---

lib/reline.rb

Fix verbose warning being emitted

---

.github/workflows/ubuntu-rvm-with-irb.yml
.github/workflows/ubuntu-rvm.yml

Fix to failed CI.
Added `bundle exec`.
Also had to revert https://github.com/ruby/reline/pull/71/files

Fix to failed CI.

---

lib/reline.rb
lib/reline/line_editor.rb

There is already the possibility to set Reline.completion_append_character.
However, it is not used by the line editor.

Implement completion_append_character

---

lib/reline/ansi.rb

`Reline::ANSI.prep` and `Reline::ANSI.deprep` call `stty` command against the process's stdin, not the assigned `input`.

Consider Reline::ANSI.input at prep

---

lib/reline/ansi.rb

ref. https://bugs.ruby-lang.org/issues/16510
Technical information: http://blog.bachi.net/?p=2082

Support gnome style home end

---

.github/workflows/reline.yml

Actions is kind of a moving target, as many changes are still occurring.  This PR combines two of the jobs into one, and also uses a more current custom action for loading Ruby.  Also, some small formatting changes.

.github/workflows/reline.yml - combine win32 with readline

---

lib/reline/line_editor.rb
test/reline/test_key_actor_emacs.rb

This fixes https://github.com/ruby/reline/issues/139.

Add search history

---

test/reline/yamatanooroti/test_rendering.rb

because inputrc will be read when starting up

Call #start_terminal after generating temporary inputrc

---

lib/reline/line_editor.rb

Closes https://github.com/ruby/reline/issues/150.

Remove duplicated line of code

---

bin/generate_east_asian_width
lib/reline/unicode.rb
lib/reline/unicode/east_asian_width.rb

It is about three times faster to use one big regexp instead of
sequential matching.

Improve the performance of `get_mbchar_width`

---

lib/reline/unicode.rb

```ruby
[{"_id"=>"5f9072a4589a06d2d74b6028",
"index"=>0,
"guid"=>"6b3051e2-dbc7-4537-bdb9-6cd7bb5358a7",
"isActive"=>true,
"balance"=>"$1,442.84",
"picture"=>"http://placehold.it/32x32",
"age"=>34,
"eyeColor"=>"blue",
"name"=>{"first"=>"Ward", "last"=>"Levy"},
"company"=>"HYPLEX",
"email"=>"ward.levy@hyplex.us",
"phone"=>"+1 (867) 568-3319",
"address"=>"867 Cobek Court, Clara, Maryland, 3254",
"about"=>
"Exercitation eu ex aliqua sit. Pariatur aliquip incididunt sint id non consectetur ullamco Lorem ea mollit duis amet sint labore. Commodo laborum labore commodo officia in cillum adipisicing esse excepteur cupidatat adipisicing ut. Non esse incididunt voluptate aliquip cillum eu aute duis laboris sit et. Amet enim …
```

Optimize regexp handling for width

---

lib/reline/line_editor.rb

```ruby
def each_top_level_statement
initialize_input
catch(:TERM_INPUT) do
loop do
begin
prompt
unless l = lex
throw :TERM_INPUT if @line == ''
else
@line_no += l.count("\n")
next if l == "\n"
@line.concat l
if @code_block_open or @ltype or @continue or @indent > 0
next
end
end
if @line != "\n"
@line.force_encoding(@io.encoding)
yield @line, @exp_line_no
end
break if @io.eof?
@line = ''
@exp_line_no = @line_no
@indent = 0
rescue TerminateLineInput
initialize_input
prompt
end
end
end
end
puts "Duration: #{Time.now - start} seconds"
```
0.33sec -> 0.22sec

Stop rerendering whole screen when adding newline at end of buffer

---

lib/reline/key_actor/emacs.rb
lib/reline/line_editor.rb
test/reline/test_key_actor_emacs.rb

Yank by em-kill-region correctly

---

lib/reline/unicode.rb
test/reline/test_key_actor_vi.rb

Delete the last char of a line by dw

---

README.md
license_of_rb-readline
reline.gemspec

This closes https://github.com/ruby/reline/issues/243.

Add acknowledgments and license for rb-readline

---

lib/reline/line_editor.rb

The vi_histedit supports multiline

---

.github/workflows/reline.yml

See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix
Update: Oh, #238 exists, and is overlapping.

CI: Fix matrix setting "cfg" to be "include" & add Ruby 3.0

---

lib/reline/windows.rb
test/reline/yamatanooroti/test_rendering.rb

This needs https://github.com/aycabta/yamatanooroti/pull/19, which is released by yamatanooroti gem 0.0.7, to test with yamatanooroti.

Use ReadConsoleInputW() instead of getwch()

---

lib/reline/ansi.rb
lib/reline/terminfo.rb

Finally, this resolves https://github.com/ruby/reline/issues/175.

Add terminfo support

---

lib/reline/ansi.rb

Apologies, I committed the first part of this directly to master by accident using GitHub editor.

Fix missing require.

---

lib/reline/windows.rb

Close https://github.com/ruby/reline/issues/317.

Add "sleep 0.1" to Windows event loop

---

lib/reline/key_stroke.rb

Remove unused using method

---

lib/reline.rb
test/reline/test_reline_key.rb

Refactoring `Reline::Key#match?` and add test.

Refactoring Reline::Key#match? and add test

---

lib/reline/line_editor.rb
lib/reline/windows.rb

I guess that `GetConsoleScreenBufferInfo` fails by unknown reason.

Check GetConsoleScreenBufferInfo result

---

lib/reline/line_editor.rb
test/reline/yamatanooroti/multiline_repl
test/reline/yamatanooroti/test_rendering.rb

I'll fix it properly later.
ref. https://github.com/ruby/irb/issues/153

Escape newlines in prompt

---

.github/workflows/reline.yml
reline.gemspec

Require Ruby >= 2.6

---

lib/reline/general_io.rb
lib/reline/line_editor.rb

Fixed https://github.com/ruby/ruby/pull/6318
Fixed https://github.com/ruby/reline/issues/446

Workaround for Alacritty and MacOS

---

lib/reline/line_editor.rb
lib/reline/version.rb
test/reline/test_key_actor_vi.rb

Fixes: https://github.com/ruby/reline/issues/468

fix vi-operator-arg

---

test/reline/yamatanooroti/termination_checker.rb

Predictive fix to https://github.com/ruby/irb/pull/503

Correspond to refactored RubyLex

---

lib/reline/windows.rb

https://github.com/ruby/reline/pull/484#issuecomment-1403877896

Revert "correct Win32API capitalization for JRuby"

---

Gemfile

Similar to https://github.com/ruby/irb/pull/518

Use the Ruby-org controlled sources for testing dependencies

---

.github/release.yml

ref: https://github.com/ruby/irb/pull/531
https://github.com/ruby/irb/releases/tag/v1.6.3

Add basic release configuration

---

Gemfile

same purpose as https://github.com/ruby/irb/pull/747

Add Racc as a development dependency

---

lib/reline/version.rb

https://github.com/ruby/reline/compare/v0.3.9...master

Bump version to 0.4.0

---

Gemfile

Same as https://github.com/ruby/irb/pull/760

Remove racc from Gemfile

---

lib/reline/line_editor.rb
test/reline/test_key_actor_vi.rb

Added the C command for vi-mode.

C for vi mode

---

lib/reline/version.rb

[Diff](https://github.com/ruby/reline/compare/v0.4.2...master)

Bump version to v0.4.3

---

lib/reline/line_editor.rb

It does not need to be nil. This will simplifies the code

Change rendered_screen.lines to non-nil

---

lib/reline/version.rb

https://github.com/ruby/reline/compare/v0.5.0...4ce247ce2b0965ef25b9d8c7f5c712e73d7e433e

Bump version to 0.5.1

---

lib/reline/version.rb

Diff: https://github.com/ruby/reline/compare/v0.5.1...501b9a6

Bump version to 0.5.2

---

lib/reline/version.rb

Diff: https://github.com/ruby/reline/compare/v0.5.2...16d82f1

Bump version to 0.5.3

---

lib/reline/version.rb

https://github.com/ruby/reline/compare/v0.5.3...0d66c33

Bump version to 0.5.4

---

lib/reline/version.rb

Diff: https://github.com/ruby/reline/compare/v0.5.4...fc9b4d2

Bump version to 0.5.5

---

lib/reline/version.rb

https://github.com/ruby/reline/compare/v0.5.5...e92dcbf51412ef1da8604bd0be921a0c76708696

Bump version to 0.5.6

---

lib/reline/version.rb

https://github.com/ruby/reline/compare/v0.5.6...4ab72f9cbdb2dfe362a16947a684a027e147568a

Bump version to 0.5.7

---

lib/reline/version.rb

https://github.com/ruby/reline/compare/v0.5.7...0b2d9fa

Bump version to 0.5.8

---

lib/reline/version.rb

https://github.com/ruby/reline/compare/v0.5.8...e3c73bb

Bump version to 0.5.9

---

lib/reline/io/windows.rb

This pull request tries to fix #545 and #676.
As described in #676, `@GetConsoleScreenBufferInfo.call(@hConsoleHandle, csbi)` fails after executing some external command.
> Fiddle.win32_last_error shows 6, which seems to map to ERROR_INVALID_HANDLE
I think console handle is somehow closed and invalidated by child process.
If that's true, (unconfirmed), we need to refresh `@hConsoleHandle` and retry the failed call.
This patch is not tested. I don't have an environment to reproduce.

[HELP WANTED] Try to fix windows and external command bug

---

lib/reline/version.rb

https://github.com/ruby/reline/compare/v0.5.9...69c95c8b6afd8f33ac1207866876bc548b30d6d1

Bump version to 0.5.10

---

test/reline/yamatanooroti/test_rendering.rb

[[Bug #20433]](https://bugs.ruby-lang.org/issues/20433)

Hash#inspect style has changed in ruby 3.4

---

test/reline/test_key_actor_emacs.rb

Some edge case of completion_append_character is fixed in #764
This pull request adds test for it.

Add completion_append_character test

---

lib/reline/version.rb

https://github.com/ruby/reline/compare/v0.5.12...8f331edb074a3bbabba7c543d415e8a63380aed1

Bump version to 0.6.0

---

lib/reline/line_editor.rb
lib/reline/unicode.rb

Fix typos in comment

---

.github/workflows/reline.yml

ref: https://github.com/ruby/irb/pull/1051

Fix CI for Ruby 2.7

---

reline.gemspec

Same as https://github.com/ruby/irb/pull/1079

Reject directory from Gem::Specification#files

---

lib/reline/version.rb

https://github.com/ruby/reline/compare/v0.6.0...183fbe0cd6c9d38772eb116bd7c090edeee01576

Bump version to 0.6.1
